{{- /* Template to define the PVC for the Drizzle migration job workspace */ -}}

{{- if .Values.job.workspace.enabled  -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-drizzle-migrate-workspace" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    # It's better to use a defined helper template for labels if available
    # Replicating common labels pattern as fallback
    app.kubernetes.io/name: {{ printf "%s-drizzle-migrate-workspace" .Release.Name }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: drizzle-migrate-workspace
spec:
  accessModes:
    - {{ .Values.job.workspace.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.job.workspace.size | default "1Gi" }}
  {{- if .Values.job.workspace.storageClass }}
  storageClassName: {{ .Values.job.workspace.storageClass }}
  {{- else }}
  # If no storageClass is specified, don't include the field to use the default
  {{- end }}
{{- end }}