{{- $hasRouteAPI := .Capabilities.APIVersions.Has "route.openshift.io/v1" -}}
{{- if and $hasRouteAPI .Values.openShiftRoute.enabled -}}
{{- $fullName := include "hasura.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
  {{- with .Values.openShiftRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.openShiftRoute.host }}
  host: {{ . | quote }}
  {{- end }}
  {{- with .Values.openShiftRoute.path }}
  path: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ $fullName }}
    {{- with .Values.openShiftRoute.to.weight }}
    weight: {{ . }}
    {{- end }}
  {{- with .Values.openShiftRoute.alternateBackends }}
  alternateBackends:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  port:
    targetPort: http
  {{- if .Values.openShiftRoute.wildcardPolicy }}
  wildcardPolicy: {{ .Values.openShiftRoute.wildcardPolicy }}
  {{- end }}
  {{- with .Values.openShiftRoute.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}