{{- if and .Values.adminSecret.enabled (not .Values.adminSecret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.fullname" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.adminSecret.key }}
  {{ .Values.adminSecret.existingSecretKey }}: {{ .Values.adminSecret.key | quote }}
  {{- else }}
  {{ .Values.adminSecret.existingSecretKey }}: {{ include "hasura.adminSecretKey" . | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.monitoring.enabled .Values.monitoring.metricsSecret }}
{{- if and .Values.adminSecret.enabled (not .Values.adminSecret.existingSecret) }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.fullname" . }}-metrics
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
type: Opaque
stringData:
  metrics-secret: {{ .Values.monitoring.metricsSecret | quote }}
{{- end }}