// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SMARTIdentityVerificationComplianceModule$Type } from "./SMARTIdentityVerificationComplianceModule";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SMARTIdentityVerificationComplianceModule"]: SMARTIdentityVerificationComplianceModule$Type;
    ["contracts/smart/modules/SMARTIdentityVerificationComplianceModule.sol:SMARTIdentityVerificationComplianceModule"]: SMARTIdentityVerificationComplianceModule$Type;
  }

  interface ContractTypesMap {
    ["SMARTIdentityVerificationComplianceModule"]: GetContractReturnType<SMARTIdentityVerificationComplianceModule$Type["abi"]>;
    ["contracts/smart/modules/SMARTIdentityVerificationComplianceModule.sol:SMARTIdentityVerificationComplianceModule"]: GetContractReturnType<SMARTIdentityVerificationComplianceModule$Type["abi"]>;
  }
}
