name: 'Setup Dependencies'
description: 'Setup all common dependencies and tools for the project'
inputs:
  harbor_user:
    description: 'Harbor username'
    required: true
  harbor_pass:
    description: 'Harbor password'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  npm_token:
    description: 'NPM registry token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v5

    - name: Set up turbo caching
      uses: namespace-actions/setup-turbocache@v0
      with:
        cache: turbo

    - name: Setup bun caches
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: |
          ./node_modules
          ./.turbo
          ./**/.turbo
          ~/.bun/install/cache
          ~/.cache/turbo
          ~/.cache/bun
          ~/.cache/foundry
          ~/.cache/helm

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor.settlemint.com
        username: ${{ inputs.harbor_user }}
        password: ${{ inputs.harbor_pass }}

    - name: Login to npm
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.github_token }}" >> ~/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" >> ~/.npmrc

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .bun-version

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        token: ${{ inputs.github_token }}

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: stable

    - name: Install Helm Docs
      shell: bash
      run: |
        brew install norwoodj/tap/helm-docs

    - name: Install Bun dependencies
      shell: bash
      run: |
        # Use Namespace's fast network for package downloads
        export BUN_CONFIG_NO_PROGRESS=true
        bun install --frozen-lockfile

    - name: Install Helm
      uses: azure/setup-helm@v4