// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AbstractIdentityComplianceModule$Type } from "./AbstractIdentityComplianceModule";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AbstractIdentityComplianceModule"]: AbstractIdentityComplianceModule$Type;
    ["contracts/smart/modules/AbstractIdentityComplianceModule.sol:AbstractIdentityComplianceModule"]: AbstractIdentityComplianceModule$Type;
  }

  interface ContractTypesMap {
    ["AbstractIdentityComplianceModule"]: GetContractReturnType<
      AbstractIdentityComplianceModule$Type["abi"]
    >;
    ["contracts/smart/modules/AbstractIdentityComplianceModule.sol:AbstractIdentityComplianceModule"]: GetContractReturnType<
      AbstractIdentityComplianceModule$Type["abi"]
    >;
  }
}
