// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKVestingAirdropImplementation$Type } from "./ATKVestingAirdropImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKVestingAirdropImplementation"]: ATKVestingAirdropImplementation$Type;
    ["contracts/addons/airdrop/vesting-airdrop/ATKVestingAirdropImplementation.sol:ATKVestingAirdropImplementation"]: ATKVestingAirdropImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKVestingAirdropImplementation"]: GetContractReturnType<
      ATKVestingAirdropImplementation$Type["abi"]
    >;
    ["contracts/addons/airdrop/vesting-airdrop/ATKVestingAirdropImplementation.sol:ATKVestingAirdropImplementation"]: GetContractReturnType<
      ATKVestingAirdropImplementation$Type["abi"]
    >;
  }
}
