// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKComplianceBypassList$Type } from "./IATKComplianceBypassList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKComplianceBypassList"]: IATKComplianceBypassList$Type;
    ["contracts/system/compliance/IATKComplianceBypassList.sol:IATKComplianceBypassList"]: IATKComplianceBypassList$Type;
  }

  interface ContractTypesMap {
    ["IATKComplianceBypassList"]: GetContractReturnType<IATKComplianceBypassList$Type["abi"]>;
    ["contracts/system/compliance/IATKComplianceBypassList.sol:IATKComplianceBypassList"]: GetContractReturnType<IATKComplianceBypassList$Type["abi"]>;
  }
}
