// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IATKComplianceBypassList$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IATKComplianceBypassList",
  "sourceName": "contracts/system/compliance/IATKComplianceBypassList.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "AddressAlreadyOnBypassList",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "AddressNotOnBypassList",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "manager",
          "type": "address"
        }
      ],
      "name": "AddressAddedToBypassList",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "manager",
          "type": "address"
        }
      ],
      "name": "AddressRemovedFromBypassList",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "address[]",
          "name": "accounts",
          "type": "address[]"
        }
      ],
      "name": "addMultipleToBypassList",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "addToBypassList",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isBypassed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "removeFromBypassList",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address[]",
          "name": "accounts",
          "type": "address[]"
        }
      ],
      "name": "removeMultipleFromBypassList",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IATKComplianceBypassList",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IATKComplianceBypassList$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/system/compliance/IATKComplianceBypassList.sol:IATKComplianceBypassList",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IATKComplianceBypassList$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IATKComplianceBypassList",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IATKComplianceBypassList$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/system/compliance/IATKComplianceBypassList.sol:IATKComplianceBypassList",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IATKComplianceBypassList$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IATKComplianceBypassList",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IATKComplianceBypassList$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/system/compliance/IATKComplianceBypassList.sol:IATKComplianceBypassList",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IATKComplianceBypassList$Type["abi"]>>;
}
