// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISMARTTokenAccessManaged$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ISMARTTokenAccessManaged",
  "sourceName": "contracts/smart/extensions/access-managed/ISMARTTokenAccessManaged.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "internalType": "bytes32",
          "name": "neededRole",
          "type": "bytes32"
        }
      ],
      "name": "AccessControlUnauthorizedAccount",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "manager",
          "type": "address"
        }
      ],
      "name": "AccessManagerSet",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "accessManager",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "role",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "hasRole",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISMARTTokenAccessManaged",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTTokenAccessManaged$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/smart/extensions/access-managed/ISMARTTokenAccessManaged.sol:ISMARTTokenAccessManaged",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTTokenAccessManaged$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISMARTTokenAccessManaged",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTTokenAccessManaged$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/smart/extensions/access-managed/ISMARTTokenAccessManaged.sol:ISMARTTokenAccessManaged",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTTokenAccessManaged$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISMARTTokenAccessManaged",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTTokenAccessManaged$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/smart/extensions/access-managed/ISMARTTokenAccessManaged.sol:ISMARTTokenAccessManaged",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTTokenAccessManaged$Type["abi"]>>;
}
