{{- if and (eq .Values.config.signingStrategy "local") (not .Values.config.existingSecret) }}
{{- if or .Values.config.privateKey .Values.config.mnemonic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-private-key
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.config.privateKey }}
  private-key: {{ .Values.config.privateKey | quote }}
  {{- end }}
  {{- if .Values.config.mnemonic }}
  PRIVATE_KEY_MNEMONIC: {{ .Values.config.mnemonic | quote }}
  {{- end }}
  {{- if .Values.config.derivationPath }}
  PRIVATE_KEY_DERIVATION_PATH: {{ .Values.config.derivationPath | quote }}
  {{- end }}
{{- end }}
{{- end }}