{{- if not .Values.privateKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "txsigner.fullname" . }}-private-key
  labels:
    {{- include "txsigner.labels" . | nindent 4 }}
stringData:
  PRIVATE_KEY_MNEMONIC: {{ .Values.privateKey.mnemonic | quote }}
  PRIVATE_KEY_DERIVATION_PATH: {{ .Values.privateKey.derivationPath | quote }}
{{- end }}