apiVersion: v1
kind: Service
metadata:
  name: {{ include "txsigner.fullname" . }}
  labels:
    {{- include "txsigner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: txsigner
      protocol: TCP
      name: txsigner
  selector:
    {{- include "txsigner.selectorLabels" . | nindent 4 }}
