// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISMARTComplianceModule$Type } from "./ISMARTComplianceModule";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISMARTComplianceModule"]: ISMARTComplianceModule$Type;
    ["contracts/smart/interface/ISMARTComplianceModule.sol:ISMARTComplianceModule"]: ISMARTComplianceModule$Type;
  }

  interface ContractTypesMap {
    ["ISMARTComplianceModule"]: GetContractReturnType<
      ISMARTComplianceModule$Type["abi"]
    >;
    ["contracts/smart/interface/ISMARTComplianceModule.sol:ISMARTComplianceModule"]: GetContractReturnType<
      ISMARTComplianceModule$Type["abi"]
    >;
  }
}
