// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISMARTRedeemable$Type } from "./ISMARTRedeemable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISMARTRedeemable"]: ISMARTRedeemable$Type;
    ["contracts/smart/extensions/redeemable/ISMARTRedeemable.sol:ISMARTRedeemable"]: ISMARTRedeemable$Type;
  }

  interface ContractTypesMap {
    ["ISMARTRedeemable"]: GetContractReturnType<ISMARTRedeemable$Type["abi"]>;
    ["contracts/smart/extensions/redeemable/ISMARTRedeemable.sol:ISMARTRedeemable"]: GetContractReturnType<
      ISMARTRedeemable$Type["abi"]
    >;
  }
}
