// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKVestingAirdrop$Type } from "./IATKVestingAirdrop";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKVestingAirdrop"]: IATKVestingAirdrop$Type;
    ["contracts/addons/airdrop/vesting-airdrop/IATKVestingAirdrop.sol:IATKVestingAirdrop"]: IATKVestingAirdrop$Type;
  }

  interface ContractTypesMap {
    ["IATKVestingAirdrop"]: GetContractReturnType<
      IATKVestingAirdrop$Type["abi"]
    >;
    ["contracts/addons/airdrop/vesting-airdrop/IATKVestingAirdrop.sol:IATKVestingAirdrop"]: GetContractReturnType<
      IATKVestingAirdrop$Type["abi"]
    >;
  }
}
