import {
  accessControlAbi,
  accessManagerAbi,
  addressBlockListAbi,
  bondAbi,
  bondFactoryAbi,
  complianceAbi,
  countryAllowListAbi,
  countryBlockListAbi,
  depositAbi,
  depositFactoryAbi,
  equityAbi,
  equityFactoryAbi,
  fixedYieldScheduleFactoryAbi,
  fundAbi,
  fundFactoryAbi,
  identityAbi,
  identityAllowListAbi,
  identityBlockListAbi,
  identityFactoryAbi,
  identityRegistryAbi,
  identityRegistryStorageAbi,
  ismartAbi,
  ismartBurnableAbi,
  ismartCappedAbi,
  ismartCustodianAbi,
  ismartFixedYieldScheduleAbi,
  ismartPausableAbi,
  ismartRedeemableAbi,
  ismartYieldAbi,
  stablecoinAbi,
  stablecoinFactoryAbi,
  systemAbi,
  tokenIdentityAbi,
  topicSchemeRegistryAbi,
  trustedIssuersRegistryAbi,
  vestingAirdropFactoryAbi,
} from "../abi";

export const ATKContracts = {
  // onboarding
  system: systemAbi,
  compliance: complianceAbi,
  identityRegistry: identityRegistryAbi,
  identityRegistryStorage: identityRegistryStorageAbi,
  trustedIssuersRegistry: trustedIssuersRegistryAbi,
  topicSchemeRegistry: topicSchemeRegistryAbi,
  identityFactory: identityFactoryAbi,
  bondFactory: bondFactoryAbi,
  depositFactory: depositFactoryAbi,
  equityFactory: equityFactoryAbi,
  fundFactory: fundFactoryAbi,
  stablecoinFactory: stablecoinFactoryAbi,
  // token
  accessManager: accessManagerAbi,
  identity: identityAbi,
  tokenIdentity: tokenIdentityAbi,
  // tokens
  deposit: depositAbi,
  equity: equityAbi,
  fund: fundAbi,
  stablecoin: stablecoinAbi,
  bond: bondAbi,
  // Open Zeppelin
  accessControl: accessControlAbi,
  // smart
  ismart: ismartAbi,
  ismartBurnable: ismartBurnableAbi,
  ismartCustodian: ismartCustodianAbi,
  ismartPausable: ismartPausableAbi,
  ismartYield: ismartYieldAbi,
  ismartFixedYieldSchedule: ismartFixedYieldScheduleAbi,
  ismartCapped: ismartCappedAbi,
  ismartRedeemable: ismartRedeemableAbi,
  // compliance modules
  countryAllowListModule: countryAllowListAbi,
  countryBlockListModule: countryBlockListAbi,
  addressBlockListModule: addressBlockListAbi,
  identityBlockListModule: identityBlockListAbi,
  identityAllowListModule: identityAllowListAbi,
  // addons
  fixedYieldScheduleFactory: fixedYieldScheduleFactoryAbi,
  vestingAirdropFactory: vestingAirdropFactoryAbi,
} as const;
