// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTHistoricalBalancesLogic$Type } from "./_SMARTHistoricalBalancesLogic";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTHistoricalBalancesLogic"]: _SMARTHistoricalBalancesLogic$Type;
    ["contracts/smart/extensions/historical-balances/internal/_SMARTHistoricalBalancesLogic.sol:_SMARTHistoricalBalancesLogic"]: _SMARTHistoricalBalancesLogic$Type;
  }

  interface ContractTypesMap {
    ["_SMARTHistoricalBalancesLogic"]: GetContractReturnType<
      _SMARTHistoricalBalancesLogic$Type["abi"]
    >;
    ["contracts/smart/extensions/historical-balances/internal/_SMARTHistoricalBalancesLogic.sol:_SMARTHistoricalBalancesLogic"]: GetContractReturnType<
      _SMARTHistoricalBalancesLogic$Type["abi"]
    >;
  }
}
