// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SignatureChecker$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SignatureChecker",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220b42584679b6ead7a6eeaa7cf8d1160323ac145ed381ceb902af1ea39e96c99ca64736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea2646970667358221220b42584679b6ead7a6eeaa7cf8d1160323ac145ed381ceb902af1ea39e96c99ca64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SignatureChecker",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SignatureChecker",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureChecker$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureChecker$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SignatureChecker",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;
}
