// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Time$Type {
  _format: "hh-sol-artifact-1";
  contractName: "Time";
  sourceName: "@openzeppelin/contracts/utils/types/Time.sol";
  abi: [];
  bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220b180e5692fe400c34908f590abe1946f547bf2afc9e114afbdfbe2012cc5671464736f6c634300081c0033";
  deployedBytecode: "0x5f80fdfea2646970667358221220b180e5692fe400c34908f590abe1946f547bf2afc9e114afbdfbe2012cc5671464736f6c634300081c0033";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Time",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/types/Time.sol:Time",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Time",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Time$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/types/Time.sol:Time",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Time$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Time",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/types/Time.sol:Time",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;
}
