// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC734$Type } from "./ERC734";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC734"]: ERC734$Type;
    ["contracts/onchainid/extensions/ERC734.sol:ERC734"]: ERC734$Type;
  }

  interface ContractTypesMap {
    ["ERC734"]: GetContractReturnType<ERC734$Type["abi"]>;
    ["contracts/onchainid/extensions/ERC734.sol:ERC734"]: GetContractReturnType<
      ERC734$Type["abi"]
    >;
  }
}
