// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKComplianceProxy$Type } from "./ATKComplianceProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKComplianceProxy"]: ATKComplianceProxy$Type;
    ["contracts/system/compliance/ATKComplianceProxy.sol:ATKComplianceProxy"]: ATKComplianceProxy$Type;
  }

  interface ContractTypesMap {
    ["ATKComplianceProxy"]: GetContractReturnType<
      ATKComplianceProxy$Type["abi"]
    >;
    ["contracts/system/compliance/ATKComplianceProxy.sol:ATKComplianceProxy"]: GetContractReturnType<
      ATKComplianceProxy$Type["abi"]
    >;
  }
}
