{{- range $path, $_ := .Files.Glob "abis/*.json" }}
{{- $filename := base $path }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $ }}-{{ $filename | trimSuffix ".json" | lower | replace "_" "-" }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{ $filename }}: |
{{ $.Files.Get $path | indent 4 }}
---
{{- end }}