apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.graphqlPort }}
      targetPort: graphql
      protocol: TCP
      name: graphql
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
