// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKDeposit$Type } from "./IATKDeposit";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKDeposit"]: IATKDeposit$Type;
    ["contracts/assets/deposit/IATKDeposit.sol:IATKDeposit"]: IATKDeposit$Type;
  }

  interface ContractTypesMap {
    ["IATKDeposit"]: GetContractReturnType<IATKDeposit$Type["abi"]>;
    ["contracts/assets/deposit/IATKDeposit.sol:IATKDeposit"]: GetContractReturnType<
      IATKDeposit$Type["abi"]
    >;
  }
}
