// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKXvPSettlementImplementation$Type } from "./ATKXvPSettlementImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKXvPSettlementImplementation"]: ATKXvPSettlementImplementation$Type;
    ["contracts/addons/xvp/ATKXvPSettlementImplementation.sol:ATKXvPSettlementImplementation"]: ATKXvPSettlementImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKXvPSettlementImplementation"]: GetContractReturnType<
      ATKXvPSettlementImplementation$Type["abi"]
    >;
    ["contracts/addons/xvp/ATKXvPSettlementImplementation.sol:ATKXvPSettlementImplementation"]: GetContractReturnType<
      ATKXvPSettlementImplementation$Type["abi"]
    >;
  }
}
