// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKSystemProxy$Type } from "./ATKSystemProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKSystemProxy"]: ATKSystemProxy$Type;
    ["contracts/system/ATKSystemProxy.sol:ATKSystemProxy"]: ATKSystemProxy$Type;
  }

  interface ContractTypesMap {
    ["ATKSystemProxy"]: GetContractReturnType<ATKSystemProxy$Type["abi"]>;
    ["contracts/system/ATKSystemProxy.sol:ATKSystemProxy"]: GetContractReturnType<ATKSystemProxy$Type["abi"]>;
  }
}
