// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTCollateralLogic$Type } from "./_SMARTCollateralLogic";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTCollateralLogic"]: _SMARTCollateralLogic$Type;
    ["smart-protocol/contracts/extensions/collateral/internal/_SMARTCollateralLogic.sol:_SMARTCollateralLogic"]: _SMARTCollateralLogic$Type;
  }

  interface ContractTypesMap {
    ["_SMARTCollateralLogic"]: GetContractReturnType<_SMARTCollateralLogic$Type["abi"]>;
    ["smart-protocol/contracts/extensions/collateral/internal/_SMARTCollateralLogic.sol:_SMARTCollateralLogic"]: GetContractReturnType<_SMARTCollateralLogic$Type["abi"]>;
  }
}
