// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC735$Type } from "./ERC735";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC735"]: ERC735$Type;
    ["contracts/onchainid/extensions/ERC735.sol:ERC735"]: ERC735$Type;
  }

  interface ContractTypesMap {
    ["ERC735"]: GetContractReturnType<ERC735$Type["abi"]>;
    ["contracts/onchainid/extensions/ERC735.sol:ERC735"]: GetContractReturnType<
      ERC735$Type["abi"]
    >;
  }
}
