apiVersion: v2
name: portal
description: >
  Portal is a comprehensive blockchain data management and querying service that
  provides

  real-time access to on-chain data through GraphQL APIs. It serves as the
  central data

  access layer for the Asset Tokenization Kit, offering high-performance
  queries, data

  synchronization, and API endpoints for frontend applications and external
  integrations.
type: application
version: 2.0.0-beta.2
appVersion: 2.0.0-beta.2
icon: https://console.settlemint.com/android-chrome-512x512.png
home: https://settlemint.com/
sources:
  - https://github.com/settlemint/starterkit-asset-tokenization
deprecated: false
kubeVersion: ">=1.21.0-0"
keywords:
  - portal
  - graphql
  - api
  - blockchain
  - data
  - query
  - web3
  - infrastructure
  - asset-tokenization
  - defi
  - settlemint
  - postgresql
  - redis
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
