// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKXvPSettlementFactoryImplementation$Type } from "./ATKXvPSettlementFactoryImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKXvPSettlementFactoryImplementation"]: ATKXvPSettlementFactoryImplementation$Type;
    ["contracts/addons/xvp/ATKXvPSettlementFactoryImplementation.sol:ATKXvPSettlementFactoryImplementation"]: ATKXvPSettlementFactoryImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKXvPSettlementFactoryImplementation"]: GetContractReturnType<
      ATKXvPSettlementFactoryImplementation$Type["abi"]
    >;
    ["contracts/addons/xvp/ATKXvPSettlementFactoryImplementation.sol:ATKXvPSettlementFactoryImplementation"]: GetContractReturnType<
      ATKXvPSettlementFactoryImplementation$Type["abi"]
    >;
  }
}
