// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTBurnableAuthorizationHooks$Type } from "./_SMARTBurnableAuthorizationHooks";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTBurnableAuthorizationHooks"]: _SMARTBurnableAuthorizationHooks$Type;
    ["smart-protocol/contracts/extensions/burnable/internal/_SMARTBurnableAuthorizationHooks.sol:_SMARTBurnableAuthorizationHooks"]: _SMARTBurnableAuthorizationHooks$Type;
  }

  interface ContractTypesMap {
    ["_SMARTBurnableAuthorizationHooks"]: GetContractReturnType<_SMARTBurnableAuthorizationHooks$Type["abi"]>;
    ["smart-protocol/contracts/extensions/burnable/internal/_SMARTBurnableAuthorizationHooks.sol:_SMARTBurnableAuthorizationHooks"]: GetContractReturnType<_SMARTBurnableAuthorizationHooks$Type["abi"]>;
  }
}
