import { Info, Lock, Shield } from "lucide-react";

interface SecurityMethodSelectorProps {
  isPinSelected: boolean;
  isOtpSelected: boolean;
  hasPincode: boolean;
  hasTwoFactor: boolean;
  onPinToggle: () => void;
  onOtpToggle: () => void;
  onSetupSecurity: () => void;
  hasAnySecurityMethod: boolean;
  needsToSetupAny: boolean;
}

export function SecurityMethodSelector({
  isPinSelected,
  isOtpSelected,
  hasPincode,
  hasTwoFactor,
  onPinToggle,
  onOtpToggle,
  onSetupSecurity,
  hasAnySecurityMethod,
  needsToSetupAny,
}: SecurityMethodSelectorProps) {
  return (
    <div className="space-y-6">
      <div className="space-y-4">
        <p className="text-sm text-foreground leading-relaxed">
          Just like your bank card requires a PIN to confirm payments, your
          wallet also needs protection to authorize actions securely.
        </p>

        <p className="text-sm text-foreground leading-relaxed">
          Your wallet controls access to your valuable digital assets and
          identity. To keep it safe, you can secure it with a PIN code or enable
          one-time passwords (OTP) for added protection.
        </p>
      </div>

      <div className="space-y-4">
        <div className="space-y-3">
          <div className="flex gap-3">
            <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0"></div>
            <div>
              <h4 className="font-medium text-foreground mb-1">PIN code:</h4>
              <p className="text-sm text-muted-foreground">
                A simple 6 digit code you enter on your device to quickly unlock
                your wallet. Easy and fast.
              </p>
            </div>
          </div>

          <div className="flex gap-3">
            <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0"></div>
            <div>
              <h4 className="font-medium text-foreground mb-1">
                One-Time Password (OTP):
              </h4>
              <p className="text-sm text-muted-foreground">
                A time-based code generated by an authenticator app on your
                phone. Offers stronger security by requiring a unique code each
                time you log in.
              </p>
            </div>
          </div>
        </div>

        <p className="text-sm text-foreground leading-relaxed">
          You can choose one or both options. The more layers you add, the safer
          your wallet becomes.
        </p>

        {/* Security method toggle buttons */}
        <div className="flex gap-4 mt-6">
          {/* PIN Code Toggle */}
          <div
            className={`flex-1 p-4 rounded-lg border-2 cursor-pointer transition-all duration-200 ${
              isPinSelected
                ? "border-primary bg-primary/5"
                : "border-input bg-background hover:bg-muted/50"
            }`}
            onClick={onPinToggle}
          >
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <Lock className="w-5 h-5 text-primary" />
                <span className="font-medium text-foreground">PIN Code</span>
              </div>
              <div className="relative">
                <input
                  type="checkbox"
                  checked={isPinSelected}
                  onChange={onPinToggle}
                  className="w-4 h-4 text-primary bg-background border-input rounded focus:ring-ring focus:ring-2"
                />
                {hasPincode && (
                  <div className="absolute -top-1 -right-1 w-3 h-3 bg-sm-state-success rounded-full border-2 border-background"></div>
                )}
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              {hasPincode ? "Already set up" : "Fast and convenient"}
            </p>
          </div>

          {/* OTP Toggle */}
          <div
            className={`flex-1 p-4 rounded-lg border-2 cursor-pointer transition-all duration-200 ${
              isOtpSelected
                ? "border-primary bg-primary/5"
                : "border-input bg-background hover:bg-muted/50"
            }`}
            onClick={onOtpToggle}
          >
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <Shield className="w-5 h-5 text-primary" />
                <span className="font-medium text-foreground">OTP</span>
              </div>
              <div className="relative">
                <input
                  type="checkbox"
                  checked={isOtpSelected}
                  onChange={onOtpToggle}
                  className="w-4 h-4 text-primary bg-background border-input rounded focus:ring-ring focus:ring-2"
                />
                {hasTwoFactor && (
                  <div className="absolute -top-1 -right-1 w-3 h-3 bg-sm-state-success rounded-full border-2 border-background"></div>
                )}
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              {hasTwoFactor ? "Already set up" : "Maximum security"}
            </p>
          </div>
        </div>

        {/* Info box for when they have existing security */}
        {hasAnySecurityMethod && (
          <div className="rounded-lg bg-primary/10 border border-primary/20 p-4 mt-6">
            <div className="flex items-start gap-3">
              <Info className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
              <div className="flex-1">
                <p className="text-sm text-primary">
                  {hasPincode && hasTwoFactor
                    ? "You have both PIN and OTP security enabled. You can add or remove security methods, or continue to the next step."
                    : hasPincode
                      ? "You have PIN security enabled. You can add OTP for additional protection, or continue to the next step."
                      : "You have OTP security enabled. You can add PIN for quick access, or continue to the next step."}
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Setup button */}
        {needsToSetupAny && (
          <div className="flex justify-center pt-4">
            <button
              onClick={onSetupSecurity}
              className="px-6 py-3 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors"
            >
              Set up Security
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
