// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISMART$Type } from "./ISMART";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISMART"]: ISMART$Type;
    ["smart-protocol/contracts/interface/ISMART.sol:ISMART"]: ISMART$Type;
  }

  interface ContractTypesMap {
    ["ISMART"]: GetContractReturnType<ISMART$Type["abi"]>;
    ["smart-protocol/contracts/interface/ISMART.sol:ISMART"]: GetContractReturnType<ISMART$Type["abi"]>;
  }
}
