// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKIdentityFactory$Type } from "./IATKIdentityFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKIdentityFactory"]: IATKIdentityFactory$Type;
    ["contracts/system/identity-factory/IATKIdentityFactory.sol:IATKIdentityFactory"]: IATKIdentityFactory$Type;
  }

  interface ContractTypesMap {
    ["IATKIdentityFactory"]: GetContractReturnType<
      IATKIdentityFactory$Type["abi"]
    >;
    ["contracts/system/identity-factory/IATKIdentityFactory.sol:IATKIdentityFactory"]: GetContractReturnType<
      IATKIdentityFactory$Type["abi"]
    >;
  }
}
