// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AbstractAddressListComplianceModule$Type } from "./AbstractAddressListComplianceModule";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AbstractAddressListComplianceModule"]: AbstractAddressListComplianceModule$Type;
    ["contracts/smart/modules/AbstractAddressListComplianceModule.sol:AbstractAddressListComplianceModule"]: AbstractAddressListComplianceModule$Type;
  }

  interface ContractTypesMap {
    ["AbstractAddressListComplianceModule"]: GetContractReturnType<AbstractAddressListComplianceModule$Type["abi"]>;
    ["contracts/smart/modules/AbstractAddressListComplianceModule.sol:AbstractAddressListComplianceModule"]: GetContractReturnType<AbstractAddressListComplianceModule$Type["abi"]>;
  }
}
