// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IIdentity$Type } from "./IIdentity";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIdentity"]: IIdentity$Type;
    ["@onchainid/contracts/interface/IIdentity.sol:IIdentity"]: IIdentity$Type;
  }

  interface ContractTypesMap {
    ["IIdentity"]: GetContractReturnType<IIdentity$Type["abi"]>;
    ["@onchainid/contracts/interface/IIdentity.sol:IIdentity"]: GetContractReturnType<IIdentity$Type["abi"]>;
  }
}
