apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erpc.fullname" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
data:
  erpc.yaml: |
    {{- toYaml .Values.config | nindent 4 }}

