// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTCustodianLogic$Type } from "./_SMARTCustodianLogic";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTCustodianLogic"]: _SMARTCustodianLogic$Type;
    ["contracts/smart/extensions/custodian/internal/_SMARTCustodianLogic.sol:_SMARTCustodianLogic"]: _SMARTCustodianLogic$Type;
  }

  interface ContractTypesMap {
    ["_SMARTCustodianLogic"]: GetContractReturnType<_SMARTCustodianLogic$Type["abi"]>;
    ["contracts/smart/extensions/custodian/internal/_SMARTCustodianLogic.sol:_SMARTCustodianLogic"]: GetContractReturnType<_SMARTCustodianLogic$Type["abi"]>;
  }
}
