// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKTokenIdentityImplementation$Type } from "./ATKTokenIdentityImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKTokenIdentityImplementation"]: ATKTokenIdentityImplementation$Type;
    ["contracts/system/identity-factory/identities/ATKTokenIdentityImplementation.sol:ATKTokenIdentityImplementation"]: ATKTokenIdentityImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKTokenIdentityImplementation"]: GetContractReturnType<
      ATKTokenIdentityImplementation$Type["abi"]
    >;
    ["contracts/system/identity-factory/identities/ATKTokenIdentityImplementation.sol:ATKTokenIdentityImplementation"]: GetContractReturnType<
      ATKTokenIdentityImplementation$Type["abi"]
    >;
  }
}
