// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SMARTTokenAccessManaged$Type } from "./SMARTTokenAccessManaged";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SMARTTokenAccessManaged"]: SMARTTokenAccessManaged$Type;
    ["contracts/smart/extensions/access-managed/SMARTTokenAccessManaged.sol:SMARTTokenAccessManaged"]: SMARTTokenAccessManaged$Type;
  }

  interface ContractTypesMap {
    ["SMARTTokenAccessManaged"]: GetContractReturnType<SMARTTokenAccessManaged$Type["abi"]>;
    ["contracts/smart/extensions/access-managed/SMARTTokenAccessManaged.sol:SMARTTokenAccessManaged"]: GetContractReturnType<SMARTTokenAccessManaged$Type["abi"]>;
  }
}
