// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISchemaResolver$Type } from "./ISchemaResolver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISchemaResolver"]: ISchemaResolver$Type;
    ["@ethereum-attestation-service/eas-contracts/resolver/ISchemaResolver.sol:ISchemaResolver"]: ISchemaResolver$Type;
  }

  interface ContractTypesMap {
    ["ISchemaResolver"]: GetContractReturnType<ISchemaResolver$Type["abi"]>;
    ["@ethereum-attestation-service/eas-contracts/resolver/ISchemaResolver.sol:ISchemaResolver"]: GetContractReturnType<ISchemaResolver$Type["abi"]>;
  }
}
