// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC20Permit$Type } from "./IERC20Permit";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20Permit"]: IERC20Permit$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/IERC20Permit.sol:IERC20Permit"]: IERC20Permit$Type;
  }

  interface ContractTypesMap {
    ["IERC20Permit"]: GetContractReturnType<IERC20Permit$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/extensions/IERC20Permit.sol:IERC20Permit"]: GetContractReturnType<IERC20Permit$Type["abi"]>;
  }
}
