// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IAccessControlEnumerable$Type } from "./IAccessControlEnumerable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAccessControlEnumerable"]: IAccessControlEnumerable$Type;
    ["@openzeppelin/contracts/access/extensions/IAccessControlEnumerable.sol:IAccessControlEnumerable"]: IAccessControlEnumerable$Type;
  }

  interface ContractTypesMap {
    ["IAccessControlEnumerable"]: GetContractReturnType<IAccessControlEnumerable$Type["abi"]>;
    ["@openzeppelin/contracts/access/extensions/IAccessControlEnumerable.sol:IAccessControlEnumerable"]: GetContractReturnType<IAccessControlEnumerable$Type["abi"]>;
  }
}
