// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKIdentityRegistryStorageImplementation$Type } from "./ATKIdentityRegistryStorageImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKIdentityRegistryStorageImplementation"]: ATKIdentityRegistryStorageImplementation$Type;
    ["contracts/system/identity-registry-storage/ATKIdentityRegistryStorageImplementation.sol:ATKIdentityRegistryStorageImplementation"]: ATKIdentityRegistryStorageImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKIdentityRegistryStorageImplementation"]: GetContractReturnType<ATKIdentityRegistryStorageImplementation$Type["abi"]>;
    ["contracts/system/identity-registry-storage/ATKIdentityRegistryStorageImplementation.sol:ATKIdentityRegistryStorageImplementation"]: GetContractReturnType<ATKIdentityRegistryStorageImplementation$Type["abi"]>;
  }
}
