/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as PrivateOnboardingRouteImport } from './routes/_private/onboarding'
import { Route as PrivateOnboardedRouteImport } from './routes/_private/_onboarded'
import { Route as PrivateOnboardingIndexRouteImport } from './routes/_private/onboarding/index'
import { Route as PrivateOnboardingPlatformRouteImport } from './routes/_private/onboarding/platform'
import { Route as PrivateOnboardingIssuerRouteImport } from './routes/_private/onboarding/issuer'
import { Route as PrivateOnboardingInvestorRouteImport } from './routes/_private/onboarding/investor'
import { Route as PrivateOnboardedSidebarRouteImport } from './routes/_private/_onboarded/_sidebar'
import { Route as PrivateOnboardedAssetDesignerIndexRouteImport } from './routes/_private/_onboarded/asset-designer/index'
import { Route as PrivateOnboardedSidebarIndexRouteImport } from './routes/_private/_onboarded/_sidebar/index'
import { Route as PrivateOnboardedSidebarTokenStatsRouteImport } from './routes/_private/_onboarded/_sidebar/token/stats'
import { Route as PrivateOnboardedSidebarTokenFactoryAddressIndexRouteImport } from './routes/_private/_onboarded/_sidebar/token/$factoryAddress/index'
import { Route as PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRouteImport } from './routes/_private/_onboarded/_sidebar/token/$factoryAddress/$tokenAddress'
import { ServerRoute as ApiSplatServerRouteImport } from './routes/api/$'
import { ServerRoute as ApiRpcSplatServerRouteImport } from './routes/api/rpc.$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/$pathname',
  path: '/$pathname',
  getParentRoute: () => AuthRoute,
} as any)
const PrivateOnboardingRoute = PrivateOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateOnboardedRoute = PrivateOnboardedRouteImport.update({
  id: '/_onboarded',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateOnboardingIndexRoute = PrivateOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateOnboardingRoute,
} as any)
const PrivateOnboardingPlatformRoute =
  PrivateOnboardingPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => PrivateOnboardingRoute,
  } as any)
const PrivateOnboardingIssuerRoute = PrivateOnboardingIssuerRouteImport.update({
  id: '/issuer',
  path: '/issuer',
  getParentRoute: () => PrivateOnboardingRoute,
} as any)
const PrivateOnboardingInvestorRoute =
  PrivateOnboardingInvestorRouteImport.update({
    id: '/investor',
    path: '/investor',
    getParentRoute: () => PrivateOnboardingRoute,
  } as any)
const PrivateOnboardedSidebarRoute = PrivateOnboardedSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => PrivateOnboardedRoute,
} as any)
const PrivateOnboardedAssetDesignerIndexRoute =
  PrivateOnboardedAssetDesignerIndexRouteImport.update({
    id: '/asset-designer/',
    path: '/asset-designer/',
    getParentRoute: () => PrivateOnboardedRoute,
  } as any)
const PrivateOnboardedSidebarIndexRoute =
  PrivateOnboardedSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateOnboardedSidebarRoute,
  } as any)
const PrivateOnboardedSidebarTokenStatsRoute =
  PrivateOnboardedSidebarTokenStatsRouteImport.update({
    id: '/token/stats',
    path: '/token/stats',
    getParentRoute: () => PrivateOnboardedSidebarRoute,
  } as any)
const PrivateOnboardedSidebarTokenFactoryAddressIndexRoute =
  PrivateOnboardedSidebarTokenFactoryAddressIndexRouteImport.update({
    id: '/token/$factoryAddress/',
    path: '/token/$factoryAddress/',
    getParentRoute: () => PrivateOnboardedSidebarRoute,
  } as any)
const PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute =
  PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRouteImport.update({
    id: '/token/$factoryAddress/$tokenAddress',
    path: '/token/$factoryAddress/$tokenAddress',
    getParentRoute: () => PrivateOnboardedSidebarRoute,
  } as any)
const ApiSplatServerRoute = ApiSplatServerRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiRpcSplatServerRoute = ApiRpcSplatServerRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof PrivateOnboardingRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/onboarding/investor': typeof PrivateOnboardingInvestorRoute
  '/onboarding/issuer': typeof PrivateOnboardingIssuerRoute
  '/onboarding/platform': typeof PrivateOnboardingPlatformRoute
  '/onboarding/': typeof PrivateOnboardingIndexRoute
  '/': typeof PrivateOnboardedSidebarIndexRoute
  '/asset-designer': typeof PrivateOnboardedAssetDesignerIndexRoute
  '/token/stats': typeof PrivateOnboardedSidebarTokenStatsRoute
  '/token/$factoryAddress/$tokenAddress': typeof PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute
  '/token/$factoryAddress': typeof PrivateOnboardedSidebarTokenFactoryAddressIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/onboarding/investor': typeof PrivateOnboardingInvestorRoute
  '/onboarding/issuer': typeof PrivateOnboardingIssuerRoute
  '/onboarding/platform': typeof PrivateOnboardingPlatformRoute
  '/onboarding': typeof PrivateOnboardingIndexRoute
  '/': typeof PrivateOnboardedSidebarIndexRoute
  '/asset-designer': typeof PrivateOnboardedAssetDesignerIndexRoute
  '/token/stats': typeof PrivateOnboardedSidebarTokenStatsRoute
  '/token/$factoryAddress/$tokenAddress': typeof PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute
  '/token/$factoryAddress': typeof PrivateOnboardedSidebarTokenFactoryAddressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_private/_onboarded': typeof PrivateOnboardedRouteWithChildren
  '/_private/onboarding': typeof PrivateOnboardingRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/_private/_onboarded/_sidebar': typeof PrivateOnboardedSidebarRouteWithChildren
  '/_private/onboarding/investor': typeof PrivateOnboardingInvestorRoute
  '/_private/onboarding/issuer': typeof PrivateOnboardingIssuerRoute
  '/_private/onboarding/platform': typeof PrivateOnboardingPlatformRoute
  '/_private/onboarding/': typeof PrivateOnboardingIndexRoute
  '/_private/_onboarded/_sidebar/': typeof PrivateOnboardedSidebarIndexRoute
  '/_private/_onboarded/asset-designer/': typeof PrivateOnboardedAssetDesignerIndexRoute
  '/_private/_onboarded/_sidebar/token/stats': typeof PrivateOnboardedSidebarTokenStatsRoute
  '/_private/_onboarded/_sidebar/token/$factoryAddress/$tokenAddress': typeof PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute
  '/_private/_onboarded/_sidebar/token/$factoryAddress/': typeof PrivateOnboardedSidebarTokenFactoryAddressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/onboarding'
    | '/auth/$pathname'
    | '/onboarding/investor'
    | '/onboarding/issuer'
    | '/onboarding/platform'
    | '/onboarding/'
    | '/'
    | '/asset-designer'
    | '/token/stats'
    | '/token/$factoryAddress/$tokenAddress'
    | '/token/$factoryAddress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/$pathname'
    | '/onboarding/investor'
    | '/onboarding/issuer'
    | '/onboarding/platform'
    | '/onboarding'
    | '/'
    | '/asset-designer'
    | '/token/stats'
    | '/token/$factoryAddress/$tokenAddress'
    | '/token/$factoryAddress'
  id:
    | '__root__'
    | '/_private'
    | '/auth'
    | '/_private/_onboarded'
    | '/_private/onboarding'
    | '/auth/$pathname'
    | '/_private/_onboarded/_sidebar'
    | '/_private/onboarding/investor'
    | '/_private/onboarding/issuer'
    | '/_private/onboarding/platform'
    | '/_private/onboarding/'
    | '/_private/_onboarded/_sidebar/'
    | '/_private/_onboarded/asset-designer/'
    | '/_private/_onboarded/_sidebar/token/stats'
    | '/_private/_onboarded/_sidebar/token/$factoryAddress/$tokenAddress'
    | '/_private/_onboarded/_sidebar/token/$factoryAddress/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/$' | '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/$' | '/api/auth/$' | '/api/rpc/$'
  id: '__root__' | '/api/$' | '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSplatServerRoute: typeof ApiSplatServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiRpcSplatServerRoute: typeof ApiRpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/onboarding': {
      id: '/_private/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PrivateOnboardingRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/_onboarded': {
      id: '/_private/_onboarded'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateOnboardedRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/onboarding/': {
      id: '/_private/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof PrivateOnboardingIndexRouteImport
      parentRoute: typeof PrivateOnboardingRoute
    }
    '/_private/onboarding/platform': {
      id: '/_private/onboarding/platform'
      path: '/platform'
      fullPath: '/onboarding/platform'
      preLoaderRoute: typeof PrivateOnboardingPlatformRouteImport
      parentRoute: typeof PrivateOnboardingRoute
    }
    '/_private/onboarding/issuer': {
      id: '/_private/onboarding/issuer'
      path: '/issuer'
      fullPath: '/onboarding/issuer'
      preLoaderRoute: typeof PrivateOnboardingIssuerRouteImport
      parentRoute: typeof PrivateOnboardingRoute
    }
    '/_private/onboarding/investor': {
      id: '/_private/onboarding/investor'
      path: '/investor'
      fullPath: '/onboarding/investor'
      preLoaderRoute: typeof PrivateOnboardingInvestorRouteImport
      parentRoute: typeof PrivateOnboardingRoute
    }
    '/_private/_onboarded/_sidebar': {
      id: '/_private/_onboarded/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateOnboardedSidebarRouteImport
      parentRoute: typeof PrivateOnboardedRoute
    }
    '/_private/_onboarded/asset-designer/': {
      id: '/_private/_onboarded/asset-designer/'
      path: '/asset-designer'
      fullPath: '/asset-designer'
      preLoaderRoute: typeof PrivateOnboardedAssetDesignerIndexRouteImport
      parentRoute: typeof PrivateOnboardedRoute
    }
    '/_private/_onboarded/_sidebar/': {
      id: '/_private/_onboarded/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateOnboardedSidebarIndexRouteImport
      parentRoute: typeof PrivateOnboardedSidebarRoute
    }
    '/_private/_onboarded/_sidebar/token/stats': {
      id: '/_private/_onboarded/_sidebar/token/stats'
      path: '/token/stats'
      fullPath: '/token/stats'
      preLoaderRoute: typeof PrivateOnboardedSidebarTokenStatsRouteImport
      parentRoute: typeof PrivateOnboardedSidebarRoute
    }
    '/_private/_onboarded/_sidebar/token/$factoryAddress/': {
      id: '/_private/_onboarded/_sidebar/token/$factoryAddress/'
      path: '/token/$factoryAddress'
      fullPath: '/token/$factoryAddress'
      preLoaderRoute: typeof PrivateOnboardedSidebarTokenFactoryAddressIndexRouteImport
      parentRoute: typeof PrivateOnboardedSidebarRoute
    }
    '/_private/_onboarded/_sidebar/token/$factoryAddress/$tokenAddress': {
      id: '/_private/_onboarded/_sidebar/token/$factoryAddress/$tokenAddress'
      path: '/token/$factoryAddress/$tokenAddress'
      fullPath: '/token/$factoryAddress/$tokenAddress'
      preLoaderRoute: typeof PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRouteImport
      parentRoute: typeof PrivateOnboardedSidebarRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface PrivateOnboardedSidebarRouteChildren {
  PrivateOnboardedSidebarIndexRoute: typeof PrivateOnboardedSidebarIndexRoute
  PrivateOnboardedSidebarTokenStatsRoute: typeof PrivateOnboardedSidebarTokenStatsRoute
  PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute: typeof PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute
  PrivateOnboardedSidebarTokenFactoryAddressIndexRoute: typeof PrivateOnboardedSidebarTokenFactoryAddressIndexRoute
}

const PrivateOnboardedSidebarRouteChildren: PrivateOnboardedSidebarRouteChildren =
  {
    PrivateOnboardedSidebarIndexRoute: PrivateOnboardedSidebarIndexRoute,
    PrivateOnboardedSidebarTokenStatsRoute:
      PrivateOnboardedSidebarTokenStatsRoute,
    PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute:
      PrivateOnboardedSidebarTokenFactoryAddressTokenAddressRoute,
    PrivateOnboardedSidebarTokenFactoryAddressIndexRoute:
      PrivateOnboardedSidebarTokenFactoryAddressIndexRoute,
  }

const PrivateOnboardedSidebarRouteWithChildren =
  PrivateOnboardedSidebarRoute._addFileChildren(
    PrivateOnboardedSidebarRouteChildren,
  )

interface PrivateOnboardedRouteChildren {
  PrivateOnboardedSidebarRoute: typeof PrivateOnboardedSidebarRouteWithChildren
  PrivateOnboardedAssetDesignerIndexRoute: typeof PrivateOnboardedAssetDesignerIndexRoute
}

const PrivateOnboardedRouteChildren: PrivateOnboardedRouteChildren = {
  PrivateOnboardedSidebarRoute: PrivateOnboardedSidebarRouteWithChildren,
  PrivateOnboardedAssetDesignerIndexRoute:
    PrivateOnboardedAssetDesignerIndexRoute,
}

const PrivateOnboardedRouteWithChildren =
  PrivateOnboardedRoute._addFileChildren(PrivateOnboardedRouteChildren)

interface PrivateOnboardingRouteChildren {
  PrivateOnboardingInvestorRoute: typeof PrivateOnboardingInvestorRoute
  PrivateOnboardingIssuerRoute: typeof PrivateOnboardingIssuerRoute
  PrivateOnboardingPlatformRoute: typeof PrivateOnboardingPlatformRoute
  PrivateOnboardingIndexRoute: typeof PrivateOnboardingIndexRoute
}

const PrivateOnboardingRouteChildren: PrivateOnboardingRouteChildren = {
  PrivateOnboardingInvestorRoute: PrivateOnboardingInvestorRoute,
  PrivateOnboardingIssuerRoute: PrivateOnboardingIssuerRoute,
  PrivateOnboardingPlatformRoute: PrivateOnboardingPlatformRoute,
  PrivateOnboardingIndexRoute: PrivateOnboardingIndexRoute,
}

const PrivateOnboardingRouteWithChildren =
  PrivateOnboardingRoute._addFileChildren(PrivateOnboardingRouteChildren)

interface PrivateRouteChildren {
  PrivateOnboardedRoute: typeof PrivateOnboardedRouteWithChildren
  PrivateOnboardingRoute: typeof PrivateOnboardingRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateOnboardedRoute: PrivateOnboardedRouteWithChildren,
  PrivateOnboardingRoute: PrivateOnboardingRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface AuthRouteChildren {
  AuthPathnameRoute: typeof AuthPathnameRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPathnameRoute: AuthPathnameRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSplatServerRoute: ApiSplatServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiRpcSplatServerRoute: ApiRpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
