// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTRedeemableLogic$Type } from "./_SMARTRedeemableLogic";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTRedeemableLogic"]: _SMARTRedeemableLogic$Type;
    ["contracts/smart/extensions/redeemable/internal/_SMARTRedeemableLogic.sol:_SMARTRedeemableLogic"]: _SMARTRedeemableLogic$Type;
  }

  interface ContractTypesMap {
    ["_SMARTRedeemableLogic"]: GetContractReturnType<_SMARTRedeemableLogic$Type["abi"]>;
    ["contracts/smart/extensions/redeemable/internal/_SMARTRedeemableLogic.sol:_SMARTRedeemableLogic"]: GetContractReturnType<_SMARTRedeemableLogic$Type["abi"]>;
  }
}
