// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Storage$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Storage",
  "sourceName": "@onchainid/contracts/storage/Storage.sol",
  "abi": [],
  "bytecode": "0x60808060405234601e5761ffff1960065416600655603a908160248239f35b600080fdfe600080fdfea2646970667358221220fe1f7c44a5cfb4f0b84f3d674dd531453c79d47145fb70f7b29f2dc8df2c974e64736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea2646970667358221220fe1f7c44a5cfb4f0b84f3d674dd531453c79d47145fb70f7b29f2dc8df2c974e64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Storage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Storage$Type["abi"]>>;
  export function deployContract(
    contractName: "@onchainid/contracts/storage/Storage.sol:Storage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Storage$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Storage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Storage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@onchainid/contracts/storage/Storage.sol:Storage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Storage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Storage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Storage$Type["abi"]>>;
  export function getContractAt(
    contractName: "@onchainid/contracts/storage/Storage.sol:Storage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Storage$Type["abi"]>>;
}
