# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- (object) Global Docker image registry
global:
  # -- (string) Global Docker image registry
  imageRegistry: ""
  # -- (list) Global Docker registry secret names as an array
  imagePullSecrets: []
  # -- (string) Global StorageClass for Persistent Volume(s)
  storageClass: ""

# -- String to fully override common.names.fullname (string)
fullnameOverride: ""

# -- String to partially override common.names.fullname (string)
nameOverride: ""

# -- Labels to add to all deployed objects (object)
commonLabels: {}

# -- Annotations to add to all deployed objects (object)
commonAnnotations: {}

# -- (object) Redis image configuration
image:
  # -- (string) Redis image registry
  registry: docker.io
  # -- (string) Redis image repository
  repository: redis
  # -- (string) Redis image tag
  tag: "8.2.2-alpine"
  # -- (string) Redis image pull policy
  pullPolicy: IfNotPresent
  # -- Redis image pull secrets (list)
  pullSecrets: []

# -- (int) Number of Redis replicas (should be 1 for development)
replicaCount: 1

# -- (object) Service configuration
service:
  # -- (string) Service type
  type: ClusterIP
  # -- (int) Redis port
  port: 6379
  # -- (object) Service annotations
  annotations: {}
  # -- (object) Service labels
  labels: {}

# -- (object) Resources configuration
resources:
  # -- (object) Resource requests
  requests:
    # -- (string) Memory request
    memory: "64Mi"
    # -- (string) CPU request
    cpu: "40m"
  # -- (object) Resource limits
  limits:
    # -- (string) Memory limit
    memory: "128Mi"
    # -- (string) CPU limit
    cpu: "240m"

# -- (object) Persistence configuration
persistence:
  # -- (bool) Enable persistence using PVC
  enabled: true
  # -- (string) Storage class for the PVC
  storageClass: ""
  # -- (list) Access mode for the PVC
  accessModes:
    - ReadWriteOnce
  # -- (string) Size of the PVC
  size: 1Gi
  # -- (object) Annotations for the PVC
  annotations: {}

# -- (object) Redis configuration
config:
  # -- (string) Maximum memory Redis can use
  maxmemory: "256mb"
  # -- (string) Memory eviction policy
  maxmemoryPolicy: "allkeys-lru"
  # -- (string) Save DB to disk (RDB persistence)
  save: ""
  # -- (string) Append only file (AOF persistence)
  appendonly: "no"

# -- (object) Authentication
auth:
  # -- (bool) Enable authentication
  enabled: true
  # -- (string) Redis password
  password: "atk"

# -- Pod annotations (object)
podAnnotations: {}

# -- Pod labels (object)
podLabels: {}

# -- Pod security context (object)
podSecurityContext: {}

# -- Container security context (object)
containerSecurityContext: {}

# -- (object) Liveness probe configuration
livenessProbe:
  # -- Enable liveness probe (bool)
  enabled: true
  # -- Initial delay seconds (int)
  initialDelaySeconds: 30
  # -- Period seconds (int)
  periodSeconds: 10
  # -- Timeout seconds (int)
  timeoutSeconds: 5
  # -- Success threshold (int)
  successThreshold: 1
  # -- Failure threshold (int)
  failureThreshold: 3

# -- (object) Readiness probe configuration
readinessProbe:
  # -- Enable readiness probe (bool)
  enabled: true
  # -- Initial delay seconds (int)
  initialDelaySeconds: 5
  # -- Period seconds (int)
  periodSeconds: 10
  # -- Timeout seconds (int)
  timeoutSeconds: 5
  # -- Success threshold (int)
  successThreshold: 1
  # -- Failure threshold (int)
  failureThreshold: 3

# -- Node selector (object)
nodeSelector: {}

# -- Tolerations (list)
tolerations: []

# -- Affinity (object)
affinity: {}

# -- (object) Network policy configuration
networkPolicy:
  # -- Enable network policies (bool)
  enabled: false
  # -- Additional allowed pod selectors (list)
  allowedPodSelectors: []
  # -- Additional allowed namespace selectors (list)
  allowedNamespaceSelectors: []
