# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Global Docker image registry
global:
  # -- Global Docker image registry
  imageRegistry: ""
  # -- Global Docker registry secret names as an array
  imagePullSecrets: []
  # -- Global StorageClass for Persistent Volume(s)
  storageClass: ""

# -- String to fully override common.names.fullname
fullnameOverride: ""

# -- String to partially override common.names.fullname
nameOverride: ""

# -- Labels to add to all deployed objects
commonLabels: {}

# -- Annotations to add to all deployed objects
commonAnnotations: {}

# Redis image configuration
image:
  # -- Redis image registry
  registry: docker.io
  # -- Redis image repository
  repository: redis
  # -- Redis image tag
  tag: "8.2.1-alpine"
  # -- Redis image pull policy
  pullPolicy: IfNotPresent
  # -- Redis image pull secrets
  pullSecrets: []

# -- Number of Redis replicas (should be 1 for development)
replicaCount: 1

# Service configuration
service:
  # -- Service type
  type: ClusterIP
  # -- Redis port
  port: 6379
  # -- Service annotations
  annotations: {}
  # -- Service labels
  labels: {}

# Resources configuration
resources:
  # -- Resource requests
  requests:
    memory: "128Mi"
    cpu: "100m"
  # -- Resource limits
  limits:
    memory: "256Mi"
    cpu: "200m"

# Persistence configuration
persistence:
  # -- Enable persistence using PVC
  enabled: true
  # -- Storage class for the PVC
  storageClass: ""
  # -- Access mode for the PVC
  accessModes:
    - ReadWriteOnce
  # -- Size of the PVC
  size: 1Gi
  # -- Annotations for the PVC
  annotations: {}

# Redis configuration
config:
  # -- Maximum memory Redis can use
  maxmemory: "256mb"
  # -- Memory eviction policy
  maxmemoryPolicy: "allkeys-lru"
  # -- Save DB to disk (RDB persistence)
  save: ""
  # -- Append only file (AOF persistence)
  appendonly: "no"

# Authentication
auth:
  # -- Enable authentication
  enabled: true
  # -- Redis password
  password: "atk"

# -- Pod annotations
podAnnotations: {}

# -- Pod labels
podLabels: {}

# -- Pod security context
podSecurityContext:
  fsGroup: 999
  runAsNonRoot: true
  runAsUser: 999
  seccompProfile:
    type: RuntimeDefault

# -- Container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  seccompProfile:
    type: RuntimeDefault

# Liveness probe configuration
livenessProbe:
  # -- Enable liveness probe
  enabled: true
  # -- Initial delay seconds
  initialDelaySeconds: 30
  # -- Period seconds
  periodSeconds: 10
  # -- Timeout seconds
  timeoutSeconds: 5
  # -- Success threshold
  successThreshold: 1
  # -- Failure threshold
  failureThreshold: 3

# Readiness probe configuration
readinessProbe:
  # -- Enable readiness probe
  enabled: true
  # -- Initial delay seconds
  initialDelaySeconds: 5
  # -- Period seconds
  periodSeconds: 10
  # -- Timeout seconds
  timeoutSeconds: 5
  # -- Success threshold
  successThreshold: 1
  # -- Failure threshold
  failureThreshold: 3

# -- Node selector
nodeSelector: {}

# -- Tolerations
tolerations: []

# -- Affinity
affinity: {}

# Network policy configuration
networkPolicy:
  # -- Enable network policies
  enabled: false
  # -- Additional allowed pod selectors
  allowedPodSelectors: []
  # -- Additional allowed namespace selectors
  allowedNamespaceSelectors: []

