// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKTokenAccessManagerImplementation$Type } from "./ATKTokenAccessManagerImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKTokenAccessManagerImplementation"]: ATKTokenAccessManagerImplementation$Type;
    ["contracts/system/access-manager/ATKTokenAccessManagerImplementation.sol:ATKTokenAccessManagerImplementation"]: ATKTokenAccessManagerImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKTokenAccessManagerImplementation"]: GetContractReturnType<ATKTokenAccessManagerImplementation$Type["abi"]>;
    ["contracts/system/access-manager/ATKTokenAccessManagerImplementation.sol:ATKTokenAccessManagerImplementation"]: GetContractReturnType<ATKTokenAccessManagerImplementation$Type["abi"]>;
  }
}
