{
 "title": "Hyperledger Besu",
 "description": "Provides an overview of Besu nodes",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Blockchain Network",
    "query": {
     "query": "label_values(besu_blockchain_chain_head_timestamp,settlemint_com_network_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (besu_blockchain_height{settlemint_com_network_name=\"$network\"} or ethereum_blockchain_height{settlemint_com_network_name=\"$network\"})",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "max by (instance) (besu_synchronizer_best_known_block{settlemint_com_network_name=\"$network\"} or ethereum_best_known_block_number{settlemint_com_network_name=\"$network\"})"
    },
    {
     "expr": "max by (instance) ((besu_synchronizer_best_known_block{settlemint_com_network_name=\"$network\"} - besu_blockchain_height{settlemint_com_network_name=\"$network\"}) or (ethereum_best_known_block_number{settlemint_com_network_name=\"$network\"} - ethereum_blockchain_height{settlemint_com_network_name=\"$network\"}))"
    },
    {
     "expr": "max by (instance) (besu_blockchain_difficulty{settlemint_com_network_name=\"$network\"})",
     "legendFormat": "Total Difficulty"
    },
    {
     "expr": "max by (instance) ((1/rate(besu_blockchain_height{settlemint_com_network_name=\"$network\"}[5m])) or (1/rate(ethereum_blockchain_height{settlemint_com_network_name=\"$network\"}[5m])))"
    },
    {
     "expr": "max by (instance) (time() - besu_blockchain_chain_head_timestamp{settlemint_com_network_name=\"$network\"})"
    },
    {
     "expr": "max by (instance) (besu_peers_peer_count_current{settlemint_com_network_name=\"$network\"} or ethereum_peer_count{settlemint_com_network_name=\"$network\"})",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "max by (instance) ((besu_peers_peer_count_current{settlemint_com_network_name=\"$network\"} / besu_network_peers_limit{settlemint_com_network_name=\"$network\"}) or ethereum_peer_count{settlemint_com_network_name=\"$network\"} / ethereum_peer_limit{settlemint_com_network_name=\"$network\"})"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1/rate(besu_blockchain_height{settlemint_com_network_name=\"$network\"}[5m]) or 1/rate(ethereum_blockchain_height{settlemint_com_network_name=\"$network\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "besu_synchronizer_best_known_block{settlemint_com_network_name=\"$network\"} - besu_blockchain_height{settlemint_com_network_name=\"$network\"} or ethereum_best_known_block_number{settlemint_com_network_name=\"$network\"} - ethereum_blockchain_height{settlemint_com_network_name=\"$network\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{settlemint_com_network_name=\"$network\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{settlemint_com_network_name=\"$network\", area=\"heap\"} + ignoring(area) jvm_memory_used_bytes{settlemint_com_network_name=\"$network\", area=\"nonheap\"} or jvm_memory_bytes_used{settlemint_com_network_name=\"$network\", area=\"heap\"} + ignoring(area) jvm_memory_bytes_used{settlemint_com_network_name=\"$network\", area=\"nonheap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}