{
 "title": "eRPC Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "network", "query": { "query": "label_values(network)" } },
   { "name": "upstream", "query": { "query": "label_values(upstream)" } },
   { "name": "category", "query": { "query": "label_values(category)" } }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P90 Response Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, network, upstream) (rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\",network!=\"\", network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m]))) > 0",
     "legendFormat": "{{network}} / {{upstream}}"
    }
   ]
  },
  { "title": "Network-level Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network-level Requests",
   "type": "timeseries",
   "description": "Total requests received by eRPC for a specific network and method",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_request_received_total{network=~\"${network:regex}\",upstream=~\"${upstream:regexp}\",category=~\"${category:regex}\"}[1m])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level RPS",
   "type": "timeseries",
   "description": "Total requests received by eRPC for a specific network and method",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_received_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network self-imposed Rate-limited requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_self_rate_limited_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network)",
     "legendFormat": "{{project}}, {{network}}"
    }
   ]
  },
  {
   "title": "Network-level Errors",
   "type": "timeseries",
   "description": "When a request fails even after trying all upstreams and retries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_failed_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (cluster_name,network,category,error) > 0",
     "legendFormat": "{{cluster_name}}, {{network}}, {{category}}, {{error}}"
    }
   ]
  },
  {
   "title": "Network-level P99 Resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_network_request_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, network, category))",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level P90 Resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(erpc_network_request_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, network, category))",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level P50 Resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_network_request_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, network, category))",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level Multiplexed requests",
   "type": "timeseries",
   "description": "When identical requests arrive at the same time they'll be merged, this number shows number of these requests",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_multiplexed_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level Multiplexed requests",
   "type": "timeseries",
   "description": "When identical requests arrive at the same time they'll be merged, this number shows number of these requests",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_multiplexed_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category)",
     "legendFormat": "{{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Effective hedged requests",
   "type": "timeseries",
   "description": "Total hedged requests that ended up being actually faster and useful. The higher the better. If this value is too low try increasing the failsafe.hedge.quantile to higher value e.g. 0.99",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum(increase(erpc_network_hedge_discards_total{attempt!=\"1\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (project, network, upstream)) / (sum(increase(erpc_network_hedged_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream))) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Highest Latest Block",
   "type": "timeseries",
   "description": "Highest value for latest block polled from all upstreams across all replicas",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(erpc_upstream_latest_block_number{upstream=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, network)",
     "legendFormat": "{{project}}, {{network}}"
    }
   ]
  },
  {
   "title": "Highest Finalized Block",
   "type": "timeseries",
   "description": "Highest value for latest block polled from all upstreams across all replicas",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(erpc_upstream_finalized_block_number{upstream=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, network)",
     "legendFormat": "{{project}}, {{network}}"
    }
   ]
  },
  { "title": "Upstream-level Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Upstream-level Requests",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream, category, attempt)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}, attempt={{attempt}}"
    }
   ]
  },
  {
   "title": "Upstream-level RPS",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream, category)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level Remote rate-limited Requests",
   "type": "timeseries",
   "description": "Total requests that are sent to upstream but is rate-limited by the provider node",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_remote_rate_limited_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (project, network, upstream, category)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level self-imposed Ratel-limited requests",
   "type": "timeseries",
   "description": "Total requests rate-limited locally on eRPC before actually sending, based on defined budget",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_self_rate_limited_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (project, network, upstream, category)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Rate-limit budget MaxCount",
   "type": "timeseries",
   "description": "Dynamically tuned value for maxCount of different rate limit budgets. NOTE This value is SUM of all replicas (in a multiple container setup)",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (budget, method) (erpc_rate_limiter_budget_max_count)\n",
     "legendFormat": "{{budget}}, config_method={{method}}"
    }
   ]
  },
  {
   "title": "Upstream-level P99 Resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, upstream, category))",
     "legendFormat": "{{project}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level P90 Resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(erpc_upstream_request_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, upstream, category))",
     "legendFormat": "{{project}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level P50 Resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (le, project, upstream, category))",
     "legendFormat": "{{project}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level warning errors",
   "type": "timeseries",
   "description": "The failures are more tolerable (e.g. rate limited, hedge-cancellations, etc) which doesn't mean upstream is failing, therefore less alert-worthy",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"warning\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream, error) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  {
   "title": "Upstream-level critical errors",
   "type": "timeseries",
   "description": "Failures received when attempting upstream endpoints, these errors mean upstream has failures",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"critical\",network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream, category, error) > 0",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{upstream}}, {{error}}"
    }
   ]
  },
  { "title": "Upstream Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Avg. Score by Upstream",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "avg(erpc_upstream_score_overall{network=\"*\",category=\"*\",upstream=~\"${upstream:regex}\"}) by (project, upstream)",
     "legendFormat": "{{project}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Avg. Score by Method",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "avg(erpc_upstream_score_overall{network!=\"*\",category!=\"*\",upstream=~\"${upstream:regex}\"}) by (project, upstream, category)",
     "legendFormat": "{{project}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Latest Block Lag by Upstream",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(erpc_upstream_block_head_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, network, upstream) <= 5000",
     "legendFormat": "{{project}},  {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Out-of-sync latest block lag by Upstream",
   "type": "timeseries",
   "description": "A special lagging tracker showing only lags of above 5000 blocks which indicates node too far off.",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(erpc_upstream_block_head_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, upstream, network) > 5000",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Latest Block by Upstream",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(erpc_upstream_latest_block_number{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, upstream, network)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Polls",
   "type": "timeseries",
   "description": "How many times we had to Poll for latest block number. This number can go up by integrity module if debounce config is too low.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_latest_block_polled_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Finalized Block Lag by Upstream",
   "type": "timeseries",
   "description": "Difference between lowest and highest finalized block as reported by upstreams. Min/Max/Mean are values across multiple replicas (if you have erpc in a multi-container setup)",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(erpc_upstream_finalization_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, upstream, network) <= 5000",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Out-of-sync Finalized Blocks by Upstream",
   "type": "timeseries",
   "description": "A special lagging tracker showing only lags of above 5000 blocks which indicates node too far off.",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(erpc_upstream_finalization_lag{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, upstream, network) > 5000",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Finalized Block by Upstream",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(erpc_upstream_finalized_block_number{upstream!=\"*\",network!=\"\",network=~\"${network:regex}\"}) by (project, upstream, network)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized Block Polls",
   "type": "timeseries",
   "description": "How many times we had to Poll for finalized block number. ",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_finalized_block_polled_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream)",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Stale latest block by Upstream",
   "type": "timeseries",
   "description": "How many times upstream returned a stale latest block (compared to other nodes) for eth_getBlockByNumber(latest) and eth_blockNumber",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_stale_latest_block_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream, category)    ",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Stale finalized block by Upstream",
   "type": "timeseries",
   "description": "How many times upstream returned stale finalized block (compared to other nodes) for eth_getBlockByNumber(finalized) and eth_blockNumber",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_stale_finalized_block_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, upstream, category)    ",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 219 } },
  {
   "title": "Cache SET success total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_success_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category, connector, policy, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET success duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_set_success_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_set_success_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 230 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_error_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category, connector, policy, error, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{error}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET error duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_set_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_set_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-hit total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 240 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_hit_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (cluster_name, network, category, connector, policy, ttl)",
     "legendFormat": "{{cluster_name}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-hit duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_success_hit_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_success_hit_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-miss total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 250 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_miss_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[1m])) by (project, network, category, connector, policy, ttl)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-miss duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_success_miss_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_success_miss_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (le, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 260 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_error_total{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\",error!=\"ErrRecordNotFound: record not found\"}[1m])) by (project, network, category, connector, policy, ttl, error)",
     "legendFormat": "{{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, {{error}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (le, project, network, category, connector, policy, ttl, error))",
     "legendFormat": "p50 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, {{error}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_error_duration_seconds_bucket{network=~\"${network:regex}\",upstream=~\"${upstream:regex}\",category=~\"${category:regex}\"}[30s])) by (le, project, network, category, connector, policy, ttl, error))",
     "legendFormat": "p95 - {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, {{error}}, TTL={{ttl}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 } },
  {
   "title": "Unexpected panics",
   "type": "timeseries",
   "description": "These are issues that are most often edge-cases that are not covered within eRPC logic, and must be reported to the team.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_unexpected_panic_total{}[1m])) by (scope, extra, error)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}