{
 "title": "HAGraph Middleware",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(deployment_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Notifications and Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(notification_queue_recvd{namespace=\"$namespace\"}) by (channel)",
     "legendFormat": "Messages Received by {{channel}}"
    },
    {
     "expr": "sum(notification_queue_sent{namespace=\"$namespace\"}) by (channel)",
     "legendFormat": "Messages Sent by {{channel}}"
    }
   ]
  },
  {
   "title": "Deployment Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(deployment_count{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(chain_head_cache_hits)", "legendFormat": "Cache Hit" },
    { "expr": "sum(chain_head_cache_misses)", "legendFormat": "Cache Misses" },
    { "expr": "chain_head_cache_latest_block", "legendFormat": "Latest Block in Cache" },
    {
     "expr": "min(chain_head_cache_oldest_block)",
     "legendFormat": "Oldest Block in Cache"
    }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max(ethereum_chain_head_number{namespace=\"$namespace\"}) - (max(deployment_head{namespace=\"$namespace\"}) or 0)",
     "legendFormat": "Blocks behind"
    }
   ]
  },
  {
   "title": "Ethereum Chain Head",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(ethereum_chain_head_number{namespace=\"$namespace\"})",
     "legendFormat": "Network Block Height"
    },
    {
     "expr": "max(deployment_head{namespace=\"$namespace\"})",
     "legendFormat": "Indexer Block Height"
    }
   ]
  },
  {
   "title": "Subgraph Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(deployment_block_processing_duration_sum{namespace=\"$namespace\"}) / avg(deployment_block_processing_duration_count{namespace=\"$namespace\"})",
     "legendFormat": "Block Processing Duration"
    },
    {
     "expr": "deployment_blocks_processed_count{namespace=\"$namespace\"}",
     "legendFormat": "Number of Blocks Processed"
    },
    {
     "expr": "deployment_failed{namespace=\"$namespace\"}",
     "legendFormat": "Failed deployment: {{deployment}}"
    },
    {
     "expr": "avg(deployment_trigger_processing_duration_sum{namespace=\"$namespace\"}) / avg(deployment_trigger_processing_duration_count{namespace=\"$namespace\"})",
     "legendFormat": "Trigger Processing Duration"
    }
   ]
  },
  {
   "title": "GraphQL Query Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(query_execution_time_sum{status=\"success\", namespace=\"$namespace\"}) / avg(query_execution_time_count{status=\"success\", namespace=\"$namespace\"})",
     "legendFormat": "Execution Time"
    },
    {
     "expr": "avg(query_parsing_time_sum{namespace=\"$namespace\"}) / avg(query_parsing_time_count{namespace=\"$namespace\"})",
     "legendFormat": "Parsing Time"
    },
    {
     "expr": "avg(query_validation_time_sum{namespace=\"$namespace\"}) / avg(query_validation_time_count{namespace=\"$namespace\"})",
     "legendFormat": "Validation Time"
    },
    {
     "expr": "sum(query_cache_status_count{namespace=\"$namespace\"}) by (cache_status)",
     "legendFormat": "Cache Status {{cache_status}}"
    },
    {
     "expr": "avg(query_blocks_behind{namespace=\"$namespace\"})",
     "legendFormat": "Blocks Behind"
    }
   ]
  },
  {
   "title": " Database and Connection Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(store_connection_error_count{namespace=\"$namespace\"})",
     "legendFormat": "Postgres Connection Errors"
    },
    {
     "expr": "avg(store_connection_checkout_count{namespace=\"$namespace\"})",
     "legendFormat": "Checkout Count"
    },
    {
     "expr": "avg(store_connection_pool_size_count{namespace=\"$namespace\"})",
     "legendFormat": "Connection Pool Size"
    }
   ]
  }
 ]
}