name: "PR Labeler"
description: "Label PR based on conventional commit format"
inputs:
  pr_number:
    description: "Pull request number"
    required: true
  pr_title:
    description: "Pull request title"
    required: true
  pr_body:
    description: "Pull request body"
    required: false
    default: ""
  log_level:
    description: "Log verbosity (error, warn, info, debug)"
    required: false
    default: "error"

runs:
  using: "composite"
  steps:
    - name: Ensure all labels exist
      uses: actions/github-script@v7
      env:
        LOG_LEVEL: ${{ inputs.log_level }}
      with:
        script: |
          const { ensureLabelsExist } = require('${{ github.action_path }}/pr-labeler.js');
          await ensureLabelsExist({ github, context });

    - name: Analyze PR and apply labels
      uses: actions/github-script@v7
      env:
        LOG_LEVEL: ${{ inputs.log_level }}
      with:
        script: |
          const { analyzePRAndApplyLabels } = require('${{ github.action_path }}/pr-labeler.js');
          await analyzePRAndApplyLabels({
            github,
            context,
            prNumber: ${{ inputs.pr_number }},
            prTitle: ${{ toJSON(inputs.pr_title) }},
            prBody: ${{ toJSON(inputs.pr_body) }}
          });
