{{- range $key, $registry := .Values.imagePullCredentials.registries }}
  {{- if $registry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atk.imagePullSecretName" $key }}
  labels:
    {{- include "atk.labels" $ | nindent 4 }}
  annotations:
    # Ensure secrets are created before jobs/pods that might need them
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-15"
    {{- include "atk.annotations" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "atk.imagePullSecret" $registry }}

  {{- end }}
{{- end }}
