{{/* Debug: Check if we can access the credentials */}}
{{- $credentials := .Values.global.imagePullCredentials }}
{{- if $credentials }}
{{- if $credentials.registries }}
{{- range $name, $registry := $credentials.registries }}
{{- if $registry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "image-pull-secret-%s" $name }}
  namespace: {{ include "atk.common.namespace" $ }}
  labels:
    {{- include "atk.common.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "atk.common.imagePullSecret" (dict "registry" $registry.registry "username" $registry.username "password" $registry.password "email" $registry.email) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}