{{- range $key, $registry := .Values.imagePullCredentials.registries }}
  {{- if $registry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atk.imagePullSecretName" $key }}
  labels:
    {{- include "atk.labels" $ | nindent 4 }}
  annotations:
    "replicator.v1.mittwald.de/replicate-to-matching": "kots.io/app-slug=atk-platform"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "atk.imagePullSecret" $registry }}

  {{- end }}
{{- end }}
