{{/* Generate image pull secrets from credentials configuration */}}
{{- $localCredentials := .Values.imagePullCredentials }}
{{- $globalCredentials := .Values.global.imagePullCredentials }}
{{- $credentials := $globalCredentials }}
{{- if and $localCredentials $localCredentials.registries (gt (len $localCredentials.registries) 0) }}
  {{- $credentials = $localCredentials }}
{{- end }}
{{- if $credentials }}
{{- if $credentials.registries }}
{{- range $name, $registry := $credentials.registries }}
{{- if $registry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "image-pull-secret-%s" $name }}
  namespace: {{ include "atk.common.namespace" $ }}
  labels:
    {{- include "atk.common.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "atk.common.imagePullSecret" (dict "registry" $registry.registry "username" $registry.username "password" $registry.password "email" $registry.email) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}