// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISMARTYieldSchedule$Type } from "./ISMARTYieldSchedule";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISMARTYieldSchedule"]: ISMARTYieldSchedule$Type;
    ["contracts/smart/extensions/yield/schedules/ISMARTYieldSchedule.sol:ISMARTYieldSchedule"]: ISMARTYieldSchedule$Type;
  }

  interface ContractTypesMap {
    ["ISMARTYieldSchedule"]: GetContractReturnType<
      ISMARTYieldSchedule$Type["abi"]
    >;
    ["contracts/smart/extensions/yield/schedules/ISMARTYieldSchedule.sol:ISMARTYieldSchedule"]: GetContractReturnType<
      ISMARTYieldSchedule$Type["abi"]
    >;
  }
}
