// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISMARTYieldSchedule$Type {
  _format: "hh-sol-artifact-1";
  contractName: "ISMARTYieldSchedule";
  sourceName: "contracts/smart/extensions/yield/schedules/ISMARTYieldSchedule.sol";
  abi: [
    {
      inputs: [];
      name: "startDate";
      outputs: [
        {
          internalType: "uint256";
          name: "startDateTimestamp";
          type: "uint256";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISMARTYieldSchedule",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTYieldSchedule$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/smart/extensions/yield/schedules/ISMARTYieldSchedule.sol:ISMARTYieldSchedule",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTYieldSchedule$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISMARTYieldSchedule",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTYieldSchedule$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/smart/extensions/yield/schedules/ISMARTYieldSchedule.sol:ISMARTYieldSchedule",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTYieldSchedule$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISMARTYieldSchedule",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTYieldSchedule$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/smart/extensions/yield/schedules/ISMARTYieldSchedule.sol:ISMARTYieldSchedule",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTYieldSchedule$Type["abi"]>>;
}
