import { THEME_TOKENS, type ThemeToken } from "@/components/theme/schema";

export const PALETTE_TOKENS: readonly ThemeToken[] = [...THEME_TOKENS];

export const FONT_PREVIEW_TEXT =
  "The quick brown fox jumps over the lazy dog — 0123456789.";

export const GOOGLE_SANS_FONTS: readonly string[] = [
  "Roboto",
  "Roboto Flex",
  "Roboto Condensed",
  "Inter",
  "Open Sans",
  "Work Sans",
  "Noto Sans",
  "Noto Sans JP",
  "Noto Sans KR",
  "Noto Sans SC",
  "Poppins",
  "Lato",
  "Manrope",
  "DM Sans",
  "Figtree",
  "Mulish",
  "Nunito",
  "Nunito Sans",
  "Urbanist",
  "Lexend",
  "Public Sans",
  "Barlow",
  "Barlow Condensed",
  "Outfit",
  "Source Sans 3",
  "Plus Jakarta Sans",
  "Quicksand",
  "Heebo",
  "Karla",
  "Epilogue",
  "Sora",
  "Montserrat",
  "IBM Plex Sans",
  "Cabinet Grotesk",
  "Be Vietnam Pro",
  "Archivo",
  "Mulish",
  "Hind",
] as const;

export const GOOGLE_MONO_FONTS: readonly string[] = [
  "Roboto Mono",
  "Space Mono",
  "JetBrains Mono",
  "IBM Plex Mono",
  "Fira Code",
  "Source Code Pro",
  "Anonymous Pro",
  "Red Hat Mono",
  "Overpass Mono",
  "Ubuntu Mono",
  "Cascadia Code",
  "PT Mono",
  "Spline Sans Mono",
  "Martian Mono",
  "DM Mono",
  "Sono",
  "Inconsolata",
  "Nanum Gothic Coding",
  "JetBrains Mono",
] as const;
