// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKXvPSettlement$Type } from "./IATKXvPSettlement";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKXvPSettlement"]: IATKXvPSettlement$Type;
    ["contracts/addons/xvp/IATKXvPSettlement.sol:IATKXvPSettlement"]: IATKXvPSettlement$Type;
  }

  interface ContractTypesMap {
    ["IATKXvPSettlement"]: GetContractReturnType<IATKXvPSettlement$Type["abi"]>;
    ["contracts/addons/xvp/IATKXvPSettlement.sol:IATKXvPSettlement"]: GetContractReturnType<IATKXvPSettlement$Type["abi"]>;
  }
}
