// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ATKSystemRoles$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ATKSystemRoles",
  "sourceName": "contracts/system/ATKSystemRoles.sol",
  "abi": [
    {
      "inputs": [],
      "name": "BYPASS_LIST_MANAGER_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "CLAIM_MANAGER_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "DEFAULT_ADMIN_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "DEPLOYER_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "IDENTITY_ISSUER_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "IMPLEMENTATION_MANAGER_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "MANAGE_REGISTRIES_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "REGISTRAR_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "STORAGE_MODIFIER_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "TOKEN_IDENTITY_ISSUER_ADMIN_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "TOKEN_IDENTITY_ISSUER_ROLE",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x608080604052346019576102f4908161001e823930815050f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081635a129a8a1461028b575080639f4530df14610256578063a217fddf14610241578063a7da5cd51461020c578063aa683370146101d7578063c34e09f0146101a2578063c65490d21461016d578063c958113714610138578063ecd0026114610103578063f68e9553146100ce5763fd27264614610095575f80fd5b5f3660031901126100ca5760206040517ff926905b211c4fe59c7d68bb001aa504586558fd2888c1ea46e1b382450050cf8152f35b5f80fd5b5f3660031901126100ca5760206040517fedcc084d3dcd65a1f7f23c65c46722faca6953d28e43150a467cf43e5c3092388152f35b5f3660031901126100ca5760206040517ffc425f2263d0df187444b70e47283d622c70181c5baebb1306a01edba1ce184c8152f35b5f3660031901126100ca5760206040517feca77a5bbbcf8baa6d8f93054311a3e6672f982247f67ba40cb896ecf1992aec8152f35b5f3660031901126100ca5760206040517f3878ec43b99c41b142f55c5c47e7aa371ea82865d891af952bc6234dbce14f188152f35b5f3660031901126100ca5760206040517fab55121422db2e83f3da68f1a86ef03984cbd0d4c289dad3bc39e9ccee18e4118152f35b5f3660031901126100ca5760206040517f5d6fb899ea6f7759b4c48caf04de64c7c9bd9cbb87888fa6007adffafe90bb858152f35b5f3660031901126100ca5760206040517f7c42e8dffc95f75177e883ddc14f7ed7caa053d3f0d4e84d6b7f0b0033223dcb8152f35b5f3660031901126100ca5760206040515f8152f35b5f3660031901126100ca5760206040517feaeeb45c1b9029a6e392e1e7aa6f4af6bd8111f85c32809598bc9903a16227a38152f35b5f3660031901126100ca57807fecaefa0171c08a6ded02d98b9432940d3852ef2c7f5007661eb8de37c5a1adc560209252f3fea264697066735822122019d8fd52c6daddce393cdf27ffa9ef724f6da9e40cb82496c3f707fa67aed95f64736f6c634300081c0033",
  "deployedBytecode": "0x6080806040526004361015610012575f80fd5b5f3560e01c9081635a129a8a1461028b575080639f4530df14610256578063a217fddf14610241578063a7da5cd51461020c578063aa683370146101d7578063c34e09f0146101a2578063c65490d21461016d578063c958113714610138578063ecd0026114610103578063f68e9553146100ce5763fd27264614610095575f80fd5b5f3660031901126100ca5760206040517ff926905b211c4fe59c7d68bb001aa504586558fd2888c1ea46e1b382450050cf8152f35b5f80fd5b5f3660031901126100ca5760206040517fedcc084d3dcd65a1f7f23c65c46722faca6953d28e43150a467cf43e5c3092388152f35b5f3660031901126100ca5760206040517ffc425f2263d0df187444b70e47283d622c70181c5baebb1306a01edba1ce184c8152f35b5f3660031901126100ca5760206040517feca77a5bbbcf8baa6d8f93054311a3e6672f982247f67ba40cb896ecf1992aec8152f35b5f3660031901126100ca5760206040517f3878ec43b99c41b142f55c5c47e7aa371ea82865d891af952bc6234dbce14f188152f35b5f3660031901126100ca5760206040517fab55121422db2e83f3da68f1a86ef03984cbd0d4c289dad3bc39e9ccee18e4118152f35b5f3660031901126100ca5760206040517f5d6fb899ea6f7759b4c48caf04de64c7c9bd9cbb87888fa6007adffafe90bb858152f35b5f3660031901126100ca5760206040517f7c42e8dffc95f75177e883ddc14f7ed7caa053d3f0d4e84d6b7f0b0033223dcb8152f35b5f3660031901126100ca5760206040515f8152f35b5f3660031901126100ca5760206040517feaeeb45c1b9029a6e392e1e7aa6f4af6bd8111f85c32809598bc9903a16227a38152f35b5f3660031901126100ca57807fecaefa0171c08a6ded02d98b9432940d3852ef2c7f5007661eb8de37c5a1adc560209252f3fea264697066735822122019d8fd52c6daddce393cdf27ffa9ef724f6da9e40cb82496c3f707fa67aed95f64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ATKSystemRoles",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ATKSystemRoles$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/system/ATKSystemRoles.sol:ATKSystemRoles",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ATKSystemRoles$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ATKSystemRoles",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ATKSystemRoles$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/system/ATKSystemRoles.sol:ATKSystemRoles",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ATKSystemRoles$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ATKSystemRoles",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ATKSystemRoles$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/system/ATKSystemRoles.sol:ATKSystemRoles",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ATKSystemRoles$Type["abi"]>>;
}
