// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ATKAssetProxy$Type {
  _format: "hh-sol-artifact-1";
  contractName: "ATKAssetProxy";
  sourceName: "contracts/assets/ATKAssetProxy.sol";
  abi: [
    {
      inputs: [];
      name: "ETHTransfersNotAllowed";
      type: "error";
    },
    {
      inputs: [];
      name: "InvalidTokenFactoryAddress";
      type: "error";
    },
    {
      inputs: [];
      name: "TokenImplementationNotSet";
      type: "error";
    },
    {
      stateMutability: "payable";
      type: "fallback";
    },
    {
      stateMutability: "payable";
      type: "receive";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ATKAssetProxy",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ATKAssetProxy$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/assets/ATKAssetProxy.sol:ATKAssetProxy",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ATKAssetProxy$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ATKAssetProxy",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ATKAssetProxy$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/assets/ATKAssetProxy.sol:ATKAssetProxy",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ATKAssetProxy$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ATKAssetProxy",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ATKAssetProxy$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/assets/ATKAssetProxy.sol:ATKAssetProxy",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ATKAssetProxy$Type["abi"]>>;
}
