// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AbstractCountryComplianceModule$Type } from "./AbstractCountryComplianceModule";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AbstractCountryComplianceModule"]: AbstractCountryComplianceModule$Type;
    ["smart-protocol/contracts/compliance/AbstractCountryComplianceModule.sol:AbstractCountryComplianceModule"]: AbstractCountryComplianceModule$Type;
  }

  interface ContractTypesMap {
    ["AbstractCountryComplianceModule"]: GetContractReturnType<AbstractCountryComplianceModule$Type["abi"]>;
    ["smart-protocol/contracts/compliance/AbstractCountryComplianceModule.sol:AbstractCountryComplianceModule"]: GetContractReturnType<AbstractCountryComplianceModule$Type["abi"]>;
  }
}
