apiVersion: v2
name: besu-network
description: A Helm chart for the besu network components
type: application
version: 1.0.6-pr-pr
appVersion: 1.0.6-pr-pr
icon: https://console.settlemint.com/android-chrome-512x512.png
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
dependencies:
  - name: besu-genesis
    version: 1.0.6-pr
  - name: besu-node
    alias: besu-validator-1
    version: 1.0.6-pr
    condition: besu-validator-1.enabled
  - name: besu-node
    alias: besu-validator-2
    version: 1.0.6-pr
    condition: besu-validator-2.enabled
  - name: besu-node
    alias: besu-validator-3
    version: 1.0.6-pr
    condition: besu-validator-3.enabled
  - name: besu-node
    alias: besu-validator-4
    version: 1.0.6-pr
    condition: besu-validator-4.enabled
  - name: besu-node
    alias: besu-rpc-1
    version: 1.0.6-pr
    condition: besu-rpc-1.enabled
  - name: besu-node
    alias: besu-rpc-2
    version: 1.0.6-pr
    condition: besu-rpc-2.enabled
