// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKFundFactory$Type } from "./IATKFundFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKFundFactory"]: IATKFundFactory$Type;
    ["contracts/assets/fund/IATKFundFactory.sol:IATKFundFactory"]: IATKFundFactory$Type;
  }

  interface ContractTypesMap {
    ["IATKFundFactory"]: GetContractReturnType<IATKFundFactory$Type["abi"]>;
    ["contracts/assets/fund/IATKFundFactory.sol:IATKFundFactory"]: GetContractReturnType<
      IATKFundFactory$Type["abi"]
    >;
  }
}
