export const fundCategories = [
  'Global Macro',
  'Equity Hedge',
  'Event-Driven',
  'Relative Value',
  'Fixed Income Arbitrage',
  'Convertible Arbitrage',
  'Merger Arbitrage',
  'Distressed Debt',
  'Managed Futures / CTA (Commodity Trading Advisor)',
  'Quantitative/Systematic',
  'Market Neutral',
  'Activist',
  'Credit',
  'Structured Credit',
  'Emerging Markets',
  'Commodity Trading',
  'Currency / FX',
  'Multi - Strategy',
  'Fund of Funds',
  'Statistical Arbitrage',
  'High-Frequency Trading (HFT)',
  'Venture Capital (VC)',
  'Private Equity (PE)',
].sort();

export const fundClasses = [
  'Long Equity (Long Only)',
  'Short Equity',
  'Long/Short Equity',
  'Market Neutral',
  'Tactical Asset Allocation',
  'Absolute Return',
  'Income-Focused',
  'Growth-Focused',
  'Value-Focused',
  'Core / Blend',
  'Small-Cap',
  'Mid-Cap',
  'Large-Cap',
  'Momentum-Oriented',
  'Quantitative / Algorithmic',
  'Opportunistic',
  'Diversified',
  'Sector-Specific',
  'Factor-Based',
  'Regional',
  'Seed / Pre-Seed',
  'Early Stage',
  'Pre-Series B',
  'Series B / Late Stage',
].sort();
