// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKTokenIdentityProxy$Type } from "./ATKTokenIdentityProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKTokenIdentityProxy"]: ATKTokenIdentityProxy$Type;
    ["contracts/system/identity-factory/identities/ATKTokenIdentityProxy.sol:ATKTokenIdentityProxy"]: ATKTokenIdentityProxy$Type;
  }

  interface ContractTypesMap {
    ["ATKTokenIdentityProxy"]: GetContractReturnType<ATKTokenIdentityProxy$Type["abi"]>;
    ["contracts/system/identity-factory/identities/ATKTokenIdentityProxy.sol:ATKTokenIdentityProxy"]: GetContractReturnType<ATKTokenIdentityProxy$Type["abi"]>;
  }
}
