// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VotesUpgradeable$Type } from "./VotesUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VotesUpgradeable"]: VotesUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/governance/utils/VotesUpgradeable.sol:VotesUpgradeable"]: VotesUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["VotesUpgradeable"]: GetContractReturnType<VotesUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/governance/utils/VotesUpgradeable.sol:VotesUpgradeable"]: GetContractReturnType<VotesUpgradeable$Type["abi"]>;
  }
}
