{{- if .Values.blockscout.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout.fullname" . }}-blockscout-env
  labels:
    app: {{ include "blockscout.fullname" . }}-blockscout
    {{- include "blockscout.labels" . | nindent 4 }}
type: Opaque
{{- $env := dict }}
{{- $pgUrl := trim (include "blockscout.postgresql.url" (dict "context" $ "local" .Values.blockscout.postgresql)) }}
{{- range $key, $value := .Values.blockscout.env }}
  {{- $rendered := include "atk.common.tplvalues.render" (dict "value" $value "context" $) }}
  {{- $_ := set $env $key (trim $rendered) }}
{{- end }}
{{- if or (not (hasKey $env "DATABASE_URL")) (eq (trim (index $env "DATABASE_URL")) "") }}
  {{- $_ := set $env "DATABASE_URL" $pgUrl }}
{{- end }}
stringData:
  {{- range $key, $value := $env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
