{{- if .Values.blockscout.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout.fullname" . }}-blockscout-env
  labels:
    app: {{ include "blockscout.fullname" . }}-blockscout
    {{- include "blockscout.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.blockscout.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}