{{- /* OpenShift Route for exposing the Blockscout frontend service when enabled. */ -}}
{{- $hasRouteAPI := .Capabilities.APIVersions.Has "route.openshift.io/v1" -}}
{{- if and $hasRouteAPI .Values.frontend.enabled .Values.frontend.openShiftRoute.enabled -}}
{{- $fullName := printf "%s-frontend" (include "blockscout.fullname" .) -}}
{{- $routeValues := .Values.frontend.openShiftRoute -}}
{{- $targetPort := "http" -}}
{{- with $routeValues.port }}
  {{- with .targetPort }}
    {{- $targetPort = . -}}
  {{- end }}
{{- end }}
{{- $weight := "" -}}
{{- with $routeValues.to }}
  {{- with .weight }}
    {{- $weight = . -}}
  {{- end }}
{{- end }}
{{- $wildcard := default "None" $routeValues.wildcardPolicy -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    {{- include "blockscout.labels" . | nindent 4 }}
  {{- with $routeValues.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: {{ $fullName }}
    {{- if $weight }}
    weight: {{ int $weight }}
    {{- end }}
  {{- with $routeValues.alternateBackends }}
  alternateBackends:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  port:
    targetPort: {{ $targetPort }}
  {{- with $routeValues.host }}
  host: {{ . | quote }}
  {{- end }}
  {{- with $routeValues.path }}
  path: {{ . | quote }}
  {{- end }}
  {{- if $wildcard }}
  wildcardPolicy: {{ $wildcard }}
  {{- end }}
  {{- with $routeValues.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
