apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graph-node.fullname" . }}-config
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
data:
  config.toml: |
{{- include "graph-node.config" . | nindent 4 }}