apiVersion: v1
kind: Secret
metadata:
  name: thegraph-pg-secret
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
data:
  PGUSER: {{ .Values.customSecret.PGUSER | b64enc }}
  PGPASSWORD: {{ .Values.customSecret.PGPASSWORD | b64enc }}

