// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SMARTPausableUpgradeable$Type } from "./SMARTPausableUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SMARTPausableUpgradeable"]: SMARTPausableUpgradeable$Type;
    ["contracts/smart/extensions/pausable/SMARTPausableUpgradeable.sol:SMARTPausableUpgradeable"]: SMARTPausableUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["SMARTPausableUpgradeable"]: GetContractReturnType<
      SMARTPausableUpgradeable$Type["abi"]
    >;
    ["contracts/smart/extensions/pausable/SMARTPausableUpgradeable.sol:SMARTPausableUpgradeable"]: GetContractReturnType<
      SMARTPausableUpgradeable$Type["abi"]
    >;
  }
}
