// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20Permit$Type } from "./ERC20Permit";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Permit"]: ERC20Permit$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol:ERC20Permit"]: ERC20Permit$Type;
  }

  interface ContractTypesMap {
    ["ERC20Permit"]: GetContractReturnType<ERC20Permit$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol:ERC20Permit"]: GetContractReturnType<ERC20Permit$Type["abi"]>;
  }
}
