// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EnumerableSet$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EnumerableSet",
  "sourceName": "@openzeppelin/contracts/utils/structs/EnumerableSet.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220d651dff202d50a52943d107baf69833ad91d37b1b83ce54f3f1e76e615507d3164736f6c634300081c0033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220d651dff202d50a52943d107baf69833ad91d37b1b83ce54f3f1e76e615507d3164736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EnumerableSet",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableSet.sol:EnumerableSet",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EnumerableSet",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EnumerableSet$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableSet.sol:EnumerableSet",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EnumerableSet$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EnumerableSet",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableSet.sol:EnumerableSet",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;
}
