// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20Pausable$Type } from "./ERC20Pausable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Pausable"]: ERC20Pausable$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Pausable.sol:ERC20Pausable"]: ERC20Pausable$Type;
  }

  interface ContractTypesMap {
    ["ERC20Pausable"]: GetContractReturnType<ERC20Pausable$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Pausable.sol:ERC20Pausable"]: GetContractReturnType<ERC20Pausable$Type["abi"]>;
  }
}
