{{- $secretName := include "ipfs-cluster.sharedSecretName" . -}}
{{- $secretValue := dict "value" "" -}}
{{- if .Values.sharedSecret }}
  {{- $_ := set $secretValue "value" .Values.sharedSecret -}}
{{- else }}
  {{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
  {{- if and $existing $existing.data }}
    {{- $existingValue := index $existing.data "secret" -}}
    {{- if $existingValue }}
      {{- $decoded := $existingValue | b64dec -}}
      {{- if and (regexMatch "^[0-9a-fA-F]+$" $decoded) (eq (len $decoded) 64) -}}
        {{- $_ := set $secretValue "value" $decoded -}}
      {{- else -}}
        {{- $_ := set $secretValue "value" ($decoded | sha256sum) -}}
      {{- end -}}
    {{- end }}
  {{- end }}
  {{- if eq (trim (index $secretValue "value")) "" -}}
    {{- $_ := set $secretValue "value" ((randAlphaNum 32) | sha256sum) -}}
  {{- end -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "ipfs-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ index $secretValue "value" | quote }}
