// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKBondFactoryImplementation$Type } from "./ATKBondFactoryImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKBondFactoryImplementation"]: ATKBondFactoryImplementation$Type;
    ["contracts/assets/bond/ATKBondFactoryImplementation.sol:ATKBondFactoryImplementation"]: ATKBondFactoryImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKBondFactoryImplementation"]: GetContractReturnType<
      ATKBondFactoryImplementation$Type["abi"]
    >;
    ["contracts/assets/bond/ATKBondFactoryImplementation.sol:ATKBondFactoryImplementation"]: GetContractReturnType<
      ATKBondFactoryImplementation$Type["abi"]
    >;
  }
}
