// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKSystemFactory$Type } from "./IATKSystemFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKSystemFactory"]: IATKSystemFactory$Type;
    ["contracts/system/IATKSystemFactory.sol:IATKSystemFactory"]: IATKSystemFactory$Type;
  }

  interface ContractTypesMap {
    ["IATKSystemFactory"]: GetContractReturnType<IATKSystemFactory$Type["abi"]>;
    ["contracts/system/IATKSystemFactory.sol:IATKSystemFactory"]: GetContractReturnType<IATKSystemFactory$Type["abi"]>;
  }
}
