// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTCustodianAuthorizationHooks$Type } from "./_SMARTCustodianAuthorizationHooks";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTCustodianAuthorizationHooks"]: _SMARTCustodianAuthorizationHooks$Type;
    ["smart-protocol/contracts/extensions/custodian/internal/_SMARTCustodianAuthorizationHooks.sol:_SMARTCustodianAuthorizationHooks"]: _SMARTCustodianAuthorizationHooks$Type;
  }

  interface ContractTypesMap {
    ["_SMARTCustodianAuthorizationHooks"]: GetContractReturnType<_SMARTCustodianAuthorizationHooks$Type["abi"]>;
    ["smart-protocol/contracts/extensions/custodian/internal/_SMARTCustodianAuthorizationHooks.sol:_SMARTCustodianAuthorizationHooks"]: GetContractReturnType<_SMARTCustodianAuthorizationHooks$Type["abi"]>;
  }
}
