import type { FilterDetails } from "../types/filter-types";

/* Details for all the filter operators for date data type */
export const dateFilterDetails = {
  is: {
    label: "is",
    value: "is",
    target: "single",
    singularOf: "is between",
    relativeOf: "is after",
    isNegated: false,
    negation: "is before",
  },
  "is not": {
    label: "is not",
    value: "is not",
    target: "single",
    singularOf: "is not between",
    relativeOf: [
      "is",
      "is before",
      "is on or after",
      "is after",
      "is on or before",
    ],
    isNegated: true,
    negationOf: "is",
  },
  "is before": {
    label: "is before",
    value: "is before",
    target: "single",
    singularOf: "is between",
    relativeOf: [
      "is",
      "is not",
      "is on or after",
      "is after",
      "is on or before",
    ],
    isNegated: false,
    negation: "is on or after",
  },
  "is on or after": {
    label: "is on or after",
    value: "is on or after",
    target: "single",
    singularOf: "is between",
    relativeOf: ["is", "is not", "is before", "is after", "is on or before"],
    isNegated: false,
    negation: "is before",
  },
  "is after": {
    label: "is after",
    value: "is after",
    target: "single",
    singularOf: "is between",
    relativeOf: [
      "is",
      "is not",
      "is before",
      "is on or after",
      "is on or before",
    ],
    isNegated: false,
    negation: "is on or before",
  },
  "is on or before": {
    label: "is on or before",
    value: "is on or before",
    target: "single",
    singularOf: "is between",
    relativeOf: ["is", "is not", "is after", "is on or after", "is before"],
    isNegated: false,
    negation: "is after",
  },
  "is between": {
    label: "is between",
    value: "is between",
    target: "multiple",
    pluralOf: "is",
    relativeOf: "is not between",
    isNegated: false,
    negation: "is not between",
  },
  "is not between": {
    label: "is not between",
    value: "is not between",
    target: "multiple",
    pluralOf: "is not",
    relativeOf: "is between",
    isNegated: true,
    negationOf: "is between",
  },
} as const satisfies FilterDetails<"date">;
