import type { FilterDetails } from "../types/filter-types";

/* Details for all the filter operators for number data type */
export const numberFilterDetails = {
  is: {
    label: "is",
    value: "is",
    target: "single",
    relativeOf: [
      "is not",
      "is greater than",
      "is less than or equal to",
      "is less than",
      "is greater than or equal to",
    ],
    isNegated: false,
    negation: "is not",
  },
  "is not": {
    label: "is not",
    value: "is not",
    target: "single",
    relativeOf: [
      "is",
      "is greater than",
      "is less than or equal to",
      "is less than",
      "is greater than or equal to",
    ],
    isNegated: true,
    negationOf: "is",
  },
  "is greater than": {
    label: ">",
    value: "is greater than",
    target: "single",
    relativeOf: [
      "is",
      "is not",
      "is less than or equal to",
      "is less than",
      "is greater than or equal to",
    ],
    isNegated: false,
    negation: "is less than or equal to",
  },
  "is greater than or equal to": {
    label: ">=",
    value: "is greater than or equal to",
    target: "single",
    relativeOf: [
      "is",
      "is not",
      "is greater than",
      "is less than or equal to",
      "is less than",
    ],
    isNegated: false,
    negation: "is less than or equal to",
  },
  "is less than": {
    label: "<",
    value: "is less than",
    target: "single",
    relativeOf: [
      "is",
      "is not",
      "is greater than",
      "is less than or equal to",
      "is greater than or equal to",
    ],
    isNegated: false,
    negation: "is greater than",
  },
  "is less than or equal to": {
    label: "<=",
    value: "is less than or equal to",
    target: "single",
    relativeOf: [
      "is",
      "is not",
      "is greater than",
      "is less than",
      "is greater than or equal to",
    ],
    isNegated: false,
    negation: "is greater than or equal to",
  },
  "is between": {
    label: "is between",
    value: "is between",
    target: "multiple",
    relativeOf: "is not between",
    isNegated: false,
    negation: "is not between",
  },
  "is not between": {
    label: "is not between",
    value: "is not between",
    target: "multiple",
    relativeOf: "is between",
    isNegated: true,
    negationOf: "is between",
  },
} as const satisfies FilterDetails<"number">;
