// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISemver$Type } from "./ISemver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISemver"]: ISemver$Type;
    ["@ethereum-attestation-service/eas-contracts/ISemver.sol:ISemver"]: ISemver$Type;
  }

  interface ContractTypesMap {
    ["ISemver"]: GetContractReturnType<ISemver$Type["abi"]>;
    ["@ethereum-attestation-service/eas-contracts/ISemver.sol:ISemver"]: GetContractReturnType<ISemver$Type["abi"]>;
  }
}
