// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20Capped$Type } from "./ERC20Capped";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Capped"]: ERC20Capped$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Capped.sol:ERC20Capped"]: ERC20Capped$Type;
  }

  interface ContractTypesMap {
    ["ERC20Capped"]: GetContractReturnType<ERC20Capped$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Capped.sol:ERC20Capped"]: GetContractReturnType<ERC20Capped$Type["abi"]>;
  }
}
