debug: false
logLevel: info
rpcUrl: http://besu:8545
chainId: 1337
port: 8545
metricsPort: 3001
signingStrategy: local
rateLimit:
  enabled: true
  maxRequestsPerMinute: 60
  maxRequestsPerHour: 1000
queue:
  maxSize: 1000
  processingInterval: 1000
gas:
  priceStrategy: estimator
  limit: 9007199254740991
  multiplier: 1.1
nonce:
  strategy: sequential
  maxPending: 10
audit:
  enabled: true
  retentionDays: 30
cors:
  enabled: false
  methods:
    - GET
    - POST
  headers:
    - Content-Type
    - Authorization
