// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SMARTCustodianUpgradeable$Type } from "./SMARTCustodianUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SMARTCustodianUpgradeable"]: SMARTCustodianUpgradeable$Type;
    ["contracts/smart/extensions/custodian/SMARTCustodianUpgradeable.sol:SMARTCustodianUpgradeable"]: SMARTCustodianUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["SMARTCustodianUpgradeable"]: GetContractReturnType<
      SMARTCustodianUpgradeable$Type["abi"]
    >;
    ["contracts/smart/extensions/custodian/SMARTCustodianUpgradeable.sol:SMARTCustodianUpgradeable"]: GetContractReturnType<
      SMARTCustodianUpgradeable$Type["abi"]
    >;
  }
}
