// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISchemaRegistry$Type } from "./ISchemaRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISchemaRegistry"]: ISchemaRegistry$Type;
    ["@ethereum-attestation-service/eas-contracts/ISchemaRegistry.sol:ISchemaRegistry"]: ISchemaRegistry$Type;
  }

  interface ContractTypesMap {
    ["ISchemaRegistry"]: GetContractReturnType<ISchemaRegistry$Type["abi"]>;
    ["@ethereum-attestation-service/eas-contracts/ISchemaRegistry.sol:ISchemaRegistry"]: GetContractReturnType<
      ISchemaRegistry$Type["abi"]
    >;
  }
}
