// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEAS$Type } from "./IEAS";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEAS"]: IEAS$Type;
    ["@ethereum-attestation-service/eas-contracts/IEAS.sol:IEAS"]: IEAS$Type;
  }

  interface ContractTypesMap {
    ["IEAS"]: GetContractReturnType<IEAS$Type["abi"]>;
    ["@ethereum-attestation-service/eas-contracts/IEAS.sol:IEAS"]: GetContractReturnType<
      IEAS$Type["abi"]
    >;
  }
}
