// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SMARTIdentityRegistry$Type } from "./SMARTIdentityRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SMARTIdentityRegistry"]: SMARTIdentityRegistry$Type;
    ["smart-protocol/contracts/SMARTIdentityRegistry.sol:SMARTIdentityRegistry"]: SMARTIdentityRegistry$Type;
  }

  interface ContractTypesMap {
    ["SMARTIdentityRegistry"]: GetContractReturnType<SMARTIdentityRegistry$Type["abi"]>;
    ["smart-protocol/contracts/SMARTIdentityRegistry.sol:SMARTIdentityRegistry"]: GetContractReturnType<SMARTIdentityRegistry$Type["abi"]>;
  }
}
