// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISMARTCompliance$Type } from "./ISMARTCompliance";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISMARTCompliance"]: ISMARTCompliance$Type;
    ["smart-protocol/contracts/interface/ISMARTCompliance.sol:ISMARTCompliance"]: ISMARTCompliance$Type;
  }

  interface ContractTypesMap {
    ["ISMARTCompliance"]: GetContractReturnType<ISMARTCompliance$Type["abi"]>;
    ["smart-protocol/contracts/interface/ISMARTCompliance.sol:ISMARTCompliance"]: GetContractReturnType<ISMARTCompliance$Type["abi"]>;
  }
}
