{{- if .Files.Glob "files/genesis-output.json" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: contracts-genesis
  labels:
    {{- include "besu-genesis.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-15"  # Must be lower than Job's -10 to run first
data:
  genesis-output.json: |
    {{- .Files.Get "files/genesis-output.json" | nindent 4 }}
{{- end }}