apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-genesis-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "besu-genesis.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-16"  # Must be created before genesis job
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}