---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: besu-genesis-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "besu-genesis.labels" . | nindent 4 }}
    app.kubernetes.io/component: genesis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "besu-genesis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: genesis-server
  template:
    metadata:
      labels:
        {{- include "besu-genesis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: genesis-server
    spec:
      {{- include "atk.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: genesis-server
        image: "{{ .Values.genesisServer.image.registry }}/{{ .Values.genesisServer.image.repository }}:{{ .Values.genesisServer.image.tag }}"
        imagePullPolicy: {{ .Values.genesisServer.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: genesis-pvc
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        livenessProbe:
          httpGet:
            path: /genesis.json
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /genesis.json
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: genesis-pvc
        persistentVolumeClaim:
          claimName: besu-genesis-pvc
      - name: nginx-config
        configMap:
          name: besu-genesis-nginx-config