{{- $generationEnabled := true -}}
{{- if hasKey . "Values" -}}
  {{- if hasKey .Values "global" -}}
    {{- if hasKey .Values.global "besuGenesis" -}}
      {{- if hasKey .Values.global.besuGenesis "generation" -}}
        {{- if hasKey .Values.global.besuGenesis.generation "enabled" -}}
          {{- $generationEnabled = .Values.global.besuGenesis.generation.enabled -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- else if hasKey .Values "generation" -}}
    {{- if hasKey .Values.generation "enabled" -}}
      {{- $generationEnabled = .Values.generation.enabled -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $generationEnabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: besu-genesis-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "besu-genesis.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-20"
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
{{- end }}
