---
apiVersion: v1
kind: Service
metadata:
  name: besu-genesis-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "besu-genesis.labels" . | nindent 4 }}
    app.kubernetes.io/component: genesis-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "besu-genesis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genesis-server