// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AddressBlockListComplianceModule$Type } from "./AddressBlockListComplianceModule";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AddressBlockListComplianceModule"]: AddressBlockListComplianceModule$Type;
    ["contracts/smart/modules/AddressBlockListComplianceModule.sol:AddressBlockListComplianceModule"]: AddressBlockListComplianceModule$Type;
  }

  interface ContractTypesMap {
    ["AddressBlockListComplianceModule"]: GetContractReturnType<
      AddressBlockListComplianceModule$Type["abi"]
    >;
    ["contracts/smart/modules/AddressBlockListComplianceModule.sol:AddressBlockListComplianceModule"]: GetContractReturnType<
      AddressBlockListComplianceModule$Type["abi"]
    >;
  }
}
