imagePullCredentials:
  registries:
    #-- lowercase, no points or special caracters unique identifier for the registry, ghcr and docker have special meaning, but you can add more
    harbor:
      # -- Enable this if you want this chart to create an image pull secret for you
      enabled: true
      # -- The registry hosting the packages, e.g docker.io or ghcr.io
      registry: "harbor.settlemint.com"
      # -- The username to access the registry
      username: "op://platform/harbor-release/username"
      # -- The password or access token to access the registry
      password: "op://platform/harbor-release/password"
      # -- The email to access the registry
      email: "op://platform/email/username"
    #-- lowercase, no points or special caracters unique identifier for the registry, ghcr and docker have special meaning, but you can add more
    ghcr:
      # -- Enable this if you want this chart to create an image pull secret for you
      enabled: true
      # -- The registry hosting the packages, e.g docker.io or ghcr.io
      registry: "ghcr.io"
      # -- The username to access the registry
      username: "op://platform/github-commit-pat/username"
      # -- The password or access token to access the registry
      password: "op://platform/github-commit-pat/package-token-harbor"
      # -- The email to access the registry
      email: "op://platform/github-commit-pat/email"
    #-- lowercase, no points or special caracters unique identifier for the registry, ghcr and docker have special meaning, but you can add more
    docker:
      # -- Enable this if you want this chart to create an image pull secret for you
      enabled: true
      # -- The registry hosting the packages, e.g docker.io or ghcr.io
      registry: "docker.io"
      # -- The username to access the registry
      username: "op://platform/dockerhub/username"
      # -- The password or access token to access the registry
      password: "op://platform/dockerhub/credential"
      # -- The email to access the registry
      email: "op://platform/dockerhub/email"
