// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKIdentityFactoryProxy$Type } from "./ATKIdentityFactoryProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKIdentityFactoryProxy"]: ATKIdentityFactoryProxy$Type;
    ["contracts/system/identity-factory/ATKIdentityFactoryProxy.sol:ATKIdentityFactoryProxy"]: ATKIdentityFactoryProxy$Type;
  }

  interface ContractTypesMap {
    ["ATKIdentityFactoryProxy"]: GetContractReturnType<ATKIdentityFactoryProxy$Type["abi"]>;
    ["contracts/system/identity-factory/ATKIdentityFactoryProxy.sol:ATKIdentityFactoryProxy"]: GetContractReturnType<ATKIdentityFactoryProxy$Type["abi"]>;
  }
}
