// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeERC20$Type {
  _format: "hh-sol-artifact-1";
  contractName: "SafeERC20";
  sourceName: "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
  abi: [
    {
      inputs: [
        {
          internalType: "address";
          name: "spender";
          type: "address";
        },
        {
          internalType: "uint256";
          name: "currentAllowance";
          type: "uint256";
        },
        {
          internalType: "uint256";
          name: "requestedDecrease";
          type: "uint256";
        },
      ];
      name: "SafeERC20FailedDecreaseAllowance";
      type: "error";
    },
    {
      inputs: [
        {
          internalType: "address";
          name: "token";
          type: "address";
        },
      ];
      name: "SafeERC20FailedOperation";
      type: "error";
    },
  ];
  bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220cc6fdc3e51b5205d465e6011626b02a316e640b31050dffb10a2d05826a9e8a864736f6c634300081c0033";
  deployedBytecode: "0x5f80fdfea2646970667358221220cc6fdc3e51b5205d465e6011626b02a316e640b31050dffb10a2d05826a9e8a864736f6c634300081c0033";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SafeERC20",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SafeERC20",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeERC20$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeERC20$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SafeERC20",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeERC20$Type["abi"]>>;
}
