-- Create branding table for platform customization
CREATE TABLE IF NOT EXISTS "branding" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"application_title" text,
	"logo_main" text,
	"logo_sidebar" text,
	"logo_favicon" text,
	"background_light" text,
	"background_dark" text,
	"color_primary" text,
	"color_primary_hover" text,
	"color_secondary" text,
	"color_accent" text,
	"color_background_darkest" text,
	"color_background_lightest" text,
	"color_background_gradient_start" text,
	"color_background_gradient_end" text,
	"color_state_success" text,
	"color_state_success_background" text,
	"color_state_warning" text,
	"color_state_warning_background" text,
	"color_state_error" text,
	"color_state_error_background" text,
	"color_graphics_primary" text,
	"color_graphics_secondary" text,
	"color_graphics_tertiary" text,
	"color_graphics_quaternary" text,
	"color_text" text,
	"color_text_contrast" text,
	"color_border" text,
	"color_muted" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

