// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IImplementationAuthority$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IImplementationAuthority",
  "sourceName": "@onchainid/contracts/interface/IImplementationAuthority.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address",
          "name": "newAddress",
          "type": "address"
        }
      ],
      "name": "UpdatedImplementation",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "getImplementation",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_newImplementation",
          "type": "address"
        }
      ],
      "name": "updateImplementation",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IImplementationAuthority",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IImplementationAuthority$Type["abi"]>>;
  export function deployContract(
    contractName: "@onchainid/contracts/interface/IImplementationAuthority.sol:IImplementationAuthority",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IImplementationAuthority$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IImplementationAuthority",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IImplementationAuthority$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@onchainid/contracts/interface/IImplementationAuthority.sol:IImplementationAuthority",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IImplementationAuthority$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IImplementationAuthority",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IImplementationAuthority$Type["abi"]>>;
  export function getContractAt(
    contractName: "@onchainid/contracts/interface/IImplementationAuthority.sol:IImplementationAuthority",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IImplementationAuthority$Type["abi"]>>;
}
