apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dapp.fullname" . }}-workspace
  labels:
    {{- include "dapp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.job.workspace.size | default "1Gi" }}
  storageClassName: {{ .Values.job.workspace.storageClass | default "" }}