{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dapp.fullname" . }}-env
  labels:
    {{- include "dapp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnv }}
  {{- $rendered := include "atk.common.tplvalues.render" (dict "value" $val "context" $) }}
  {{ $key }}: {{ $rendered | b64enc }}
  {{- end }}
{{- end }}
