{{- if .Values.secretEnv }}
{{- $hasuraConfig := ((include "atk.datastores.postgresql.config" (dict "context" . "chartKey" "hasura")) | fromYaml) | default (dict) }}
{{- $hasuraExistingSecret := trim (default "" (index $hasuraConfig "existingSecret")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dapp.fullname" . }}-env
  labels:
    {{- include "dapp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnv }}
  {{- if not (and (eq $key "SETTLEMINT_HASURA_DATABASE_URL") (ne $hasuraExistingSecret "")) }}
    {{- $rendered := include "atk.common.tplvalues.render" (dict "value" $val "context" $) }}
  {{ $key }}: {{ $rendered | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
