apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  postgresql.conf: |
    {{- range $key, $value := .Values.postgresql_conf }}
    {{ $key }} = {{ $value }}
    {{- end }}
---
{{- if .Values.initdb.scripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-initdb
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.initdb.scripts }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}