// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC735$Type } from "./IERC735";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC735"]: IERC735$Type;
    ["@onchainid/contracts/interface/IERC735.sol:IERC735"]: IERC735$Type;
  }

  interface ContractTypesMap {
    ["IERC735"]: GetContractReturnType<IERC735$Type["abi"]>;
    ["@onchainid/contracts/interface/IERC735.sol:IERC735"]: GetContractReturnType<
      IERC735$Type["abi"]
    >;
  }
}
