// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AccessControlEnumerableUpgradeable$Type } from "./AccessControlEnumerableUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AccessControlEnumerableUpgradeable"]: AccessControlEnumerableUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/access/extensions/AccessControlEnumerableUpgradeable.sol:AccessControlEnumerableUpgradeable"]: AccessControlEnumerableUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["AccessControlEnumerableUpgradeable"]: GetContractReturnType<AccessControlEnumerableUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/access/extensions/AccessControlEnumerableUpgradeable.sol:AccessControlEnumerableUpgradeable"]: GetContractReturnType<AccessControlEnumerableUpgradeable$Type["abi"]>;
  }
}
