/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';

declare module 'gql.tada' {
 interface setupCache {
    "\n  fragment AccessControlFragment on AccessControl {\n    admin { id }\n    registrar { id }\n    claimManager { id }\n    deployer { id }\n    storageModifier { id }\n    registryManager { id }\n    governance { id }\n    supplyManagement { id }\n    custodian { id }\n    emergency { id }\n    implementationManager { id }\n    bypassListManager { id }\n  }\n":
      TadaDocumentNode<{ admin: { id: string; }[]; registrar: { id: string; }[]; claimManager: { id: string; }[]; deployer: { id: string; }[]; storageModifier: { id: string; }[]; registryManager: { id: string; }[]; governance: { id: string; }[]; supplyManagement: { id: string; }[]; custodian: { id: string; }[]; emergency: { id: string; }[]; implementationManager: { id: string; }[]; bypassListManager: { id: string; }[]; }, {}, { fragment: "AccessControlFragment"; on: "AccessControl"; masked: false; }>;
    "\n        query GetIndexingStatus {\n          _meta {\n            block {\n              number\n            }\n          }\n        }\n      ":
      TadaDocumentNode<{ _meta: { block: { number: number; }; } | null; }, {}, void>;
    "\n  query GetTokenFactories($systemAddress: ID!) {\n    system(id: $systemAddress) {\n      tokenFactoryRegistry {\n        tokenFactories {\n          id\n          name\n          accessControl {\n            ...AccessControlFragment\n          }\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ system: { tokenFactoryRegistry: { tokenFactories: { id: string; name: string; accessControl: { admin: { id: string; }[]; registrar: { id: string; }[]; claimManager: { id: string; }[]; deployer: { id: string; }[]; storageModifier: { id: string; }[]; registryManager: { id: string; }[]; governance: { id: string; }[]; supplyManagement: { id: string; }[]; custodian: { id: string; }[]; emergency: { id: string; }[]; implementationManager: { id: string; }[]; bypassListManager: { id: string; }[]; }; }[]; } | null; } | null; }, { systemAddress: string; }, void>;
    "\n  query ReadTokenQuery($id: ID!) {\n    token(id: $id) {\n      id\n      name\n      symbol\n      decimals\n      requiredClaimTopics {\n        name\n      }\n      accessControl {\n        ...AccessControlFragment\n      }\n    }\n  }\n  ":
      TadaDocumentNode<{ token: { id: string; name: string; symbol: string; decimals: number; requiredClaimTopics: { name: string; }[]; accessControl: { admin: { id: string; }[]; registrar: { id: string; }[]; claimManager: { id: string; }[]; deployer: { id: string; }[]; storageModifier: { id: string; }[]; registryManager: { id: string; }[]; governance: { id: string; }[]; supplyManagement: { id: string; }[]; custodian: { id: string; }[]; emergency: { id: string; }[]; implementationManager: { id: string; }[]; bypassListManager: { id: string; }[]; } | null; } | null; }, { id: string; }, void>;
    "\nquery ReadAccountQuery($walletAddress: ID!) {\n  account(id: $walletAddress) {\n    id\n  }\n}\n":
      TadaDocumentNode<{ account: { id: string; } | null; }, { walletAddress: string; }, void>;
    "\n  query ListTokenFactories($skip: Int!, $first: Int!, $orderBy: TokenFactory_orderBy = id, $orderDirection: OrderDirection = asc) {\n    tokenFactories(\n      skip: $skip\n      first: $first\n      orderBy: $orderBy\n      orderDirection: $orderDirection\n    ) {\n      id\n      name\n      typeId\n      hasTokens\n    }\n  }\n":
      TadaDocumentNode<{ tokenFactories: { id: string; name: string; typeId: string; hasTokens: unknown; }[]; }, { orderDirection?: "asc" | "desc" | null | undefined; orderBy?: "id" | "name" | "tokens" | "tokenFactoryRegistry" | "accessControl" | "account" | "typeId" | "accessControl__id" | "tokenFactoryRegistry__id" | "tokenFactoryRegistry__deployedInTransaction" | "account__id" | "account__isContract" | "account__country" | null | undefined; first: number; skip: number; }, void>;
    "\n  query ReadTokenFactory($id: ID!) {\n    tokenFactory(id: $id) {\n      id\n      name\n      typeId\n    }\n  }\n":
      TadaDocumentNode<{ tokenFactory: { id: string; name: string; typeId: string; } | null; }, { id: string; }, void>;
    "\n  query ListTokenQuery($skip: Int!, $first: Int!, $orderBy: Token_orderBy = id, $orderDirection: OrderDirection = asc) {\n    tokens(\n        skip: $skip\n        first: $first\n        orderBy: $orderBy\n        orderDirection: $orderDirection\n      ) {\n        id\n        name\n        symbol\n        decimals\n      }\n    }\n  ":
      TadaDocumentNode<{ tokens: { id: string; name: string; symbol: string; decimals: number; }[]; }, { orderDirection?: "asc" | "desc" | null | undefined; orderBy?: "symbol" | "type" | "id" | "name" | "bond" | "fund" | "decimals" | "tokenFactory" | "accessControl" | "requiredClaimTopics" | "account" | "identity" | "createdAt" | "accessControl__id" | "account__id" | "account__isContract" | "account__country" | "createdBy" | "createdBy__id" | "createdBy__isContract" | "createdBy__country" | "deployedInTransaction" | "identity__id" | "identity__deployedInTransaction" | "balances" | "tokenFactory__id" | "tokenFactory__name" | "tokenFactory__typeId" | "totalSupply" | "totalSupplyExact" | "pausable" | "pausable__id" | "pausable__paused" | "collateral" | "collateral__id" | "capped" | "capped__id" | "capped__cap" | "capped__capExact" | "yield_" | "yield___id" | "redeemable" | "redeemable__id" | "redeemable__redeemedAmount" | "redeemable__redeemedAmountExact" | "bond__id" | "bond__faceValue" | "bond__faceValueExact" | "bond__maturityDate" | "bond__isMatured" | "fund__id" | "fund__managementFeeBps" | "basePriceClaim" | "basePriceClaim__id" | "basePriceClaim__name" | "basePriceClaim__uri" | "basePriceClaim__revoked" | "basePriceClaim__deployedInTransaction" | "tokenComplianceModules" | null | undefined; first: number; skip: number; }, void>;
    "\n  query ReadAccountQuery($id: ID!) {\n    account(id: $id) {\n      id\n      identity {\n        claims {\n          name\n        }\n      }\n    }\n  }\n  ":
      TadaDocumentNode<{ account: { id: string; identity: { claims: { name: string; }[]; } | null; } | null; }, { id: string; }, void>;
    "\n  query findSystemForTransaction($deployedInTransaction: Bytes) {\n    systems(where: {deployedInTransaction: $deployedInTransaction}) {\n      id\n    }\n  }\n":
      TadaDocumentNode<{ systems: { id: string; }[]; }, { deployedInTransaction?: string | null | undefined; }, void>;
    "\n  query ListSystemQuery($skip: Int!, $first: Int!, $orderBy: System_orderBy = id, $orderDirection: OrderDirection = asc) {\n    systems(\n        skip: $skip\n        first: $first\n        orderBy: $orderBy\n        orderDirection: $orderDirection\n      ) {\n      id\n    }\n  }\n":
      TadaDocumentNode<{ systems: { id: string; }[]; }, { orderDirection?: "asc" | "desc" | null | undefined; orderBy?: "id" | "tokenFactoryRegistry" | "accessControl" | "account" | "accessControl__id" | "tokenFactoryRegistry__id" | "tokenFactoryRegistry__deployedInTransaction" | "account__id" | "account__isContract" | "account__country" | "deployedInTransaction" | "compliance" | "compliance__id" | "identityRegistryStorage" | "identityRegistryStorage__id" | "identityRegistryStorage__deployedInTransaction" | "identityFactory" | "identityFactory__id" | "identityFactory__deployedInTransaction" | "identityRegistry" | "identityRegistry__id" | "identityRegistry__deployedInTransaction" | "trustedIssuersRegistry" | "trustedIssuersRegistry__id" | "trustedIssuersRegistry__deployedInTransaction" | "topicSchemeRegistry" | "topicSchemeRegistry__id" | "topicSchemeRegistry__deployedInTransaction" | "complianceModuleRegistry" | "complianceModuleRegistry__id" | "complianceModuleRegistry__deployedInTransaction" | "systemAddonRegistry" | "systemAddonRegistry__id" | "systemAddonRegistry__deployedInTransaction" | null | undefined; first: number; skip: number; }, void>;
    "\n  query SystemDetails($id: ID!) {\n    system(id: $id) {\n      id\n      tokenFactoryRegistry {\n        id\n        tokenFactories {\n          id\n          name\n          typeId\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ system: { id: string; tokenFactoryRegistry: { id: string; tokenFactories: { id: string; name: string; typeId: string; }[]; } | null; } | null; }, { id: string; }, void>;
  }
}
