// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKStableCoin$Type } from "./IATKStableCoin";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKStableCoin"]: IATKStableCoin$Type;
    ["contracts/assets/stable-coin/IATKStableCoin.sol:IATKStableCoin"]: IATKStableCoin$Type;
  }

  interface ContractTypesMap {
    ["IATKStableCoin"]: GetContractReturnType<IATKStableCoin$Type["abi"]>;
    ["contracts/assets/stable-coin/IATKStableCoin.sol:IATKStableCoin"]: GetContractReturnType<IATKStableCoin$Type["abi"]>;
  }
}
