// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKIdentityImplementation$Type } from "./ATKIdentityImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKIdentityImplementation"]: ATKIdentityImplementation$Type;
    ["contracts/system/identity-factory/identities/ATKIdentityImplementation.sol:ATKIdentityImplementation"]: ATKIdentityImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKIdentityImplementation"]: GetContractReturnType<ATKIdentityImplementation$Type["abi"]>;
    ["contracts/system/identity-factory/identities/ATKIdentityImplementation.sol:ATKIdentityImplementation"]: GetContractReturnType<ATKIdentityImplementation$Type["abi"]>;
  }
}
