// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EAS$Type } from "./EAS";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EAS"]: EAS$Type;
    ["@ethereum-attestation-service/eas-contracts/EAS.sol:EAS"]: EAS$Type;
  }

  interface ContractTypesMap {
    ["EAS"]: GetContractReturnType<EAS$Type["abi"]>;
    ["@ethereum-attestation-service/eas-contracts/EAS.sol:EAS"]: GetContractReturnType<EAS$Type["abi"]>;
  }
}
