// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTBurnableLogic$Type } from "./_SMARTBurnableLogic";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTBurnableLogic"]: _SMARTBurnableLogic$Type;
    ["contracts/smart/extensions/burnable/internal/_SMARTBurnableLogic.sol:_SMARTBurnableLogic"]: _SMARTBurnableLogic$Type;
  }

  interface ContractTypesMap {
    ["_SMARTBurnableLogic"]: GetContractReturnType<_SMARTBurnableLogic$Type["abi"]>;
    ["contracts/smart/extensions/burnable/internal/_SMARTBurnableLogic.sol:_SMARTBurnableLogic"]: GetContractReturnType<_SMARTBurnableLogic$Type["abi"]>;
  }
}
