name: "Auto-Merge Management"
description: "Manage auto-merge for pull requests"
inputs:
  pr_number:
    description: "Pull request number"
    required: true
  pr_author:
    description: "Pull request author"
    required: true
  pr_author_type:
    description: "Pull request author type (User or Bot)"
    required: false
    default: "User"
  has_approval:
    description: "Whether PR has approval"
    required: true
  qa_status:
    description: "QA status (success, failed, running, pending)"
    required: true
  is_draft:
    description: "Whether PR is a draft"
    required: true
  merge_method:
    description: "Merge method (merge, squash, rebase)"
    required: false
    default: "squash"
  log_level:
    description: "Log verbosity (error, warn, info, debug)"
    required: false
    default: "error"

runs:
  using: "composite"
  steps:
    - name: Manage auto-merge for PR
      uses: actions/github-script@v8
      env:
        LOG_LEVEL: ${{ inputs.log_level }}
      with:
        script: |
          const { manageAutoMerge } = require('${{ github.action_path }}/auto-merge-manager.js');
          await manageAutoMerge({
            github,
            context,
            prNumber: ${{ inputs.pr_number }},
            prAuthor: '${{ inputs.pr_author }}',
            prAuthorType: '${{ inputs.pr_author_type }}',
            hasApproval: ${{ inputs.has_approval }},
            qaStatus: '${{ inputs.qa_status }}',
            isDraft: ${{ inputs.is_draft }},
            mergeMethod: '${{ inputs.merge_method }}'
          });
