{
 "title": "Node (Pods)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubernetes-nodes\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster_name=\"$cluster\"},node)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Requests vs Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", node=~\"$node\", resource=\"cpu\"}) / sum(kube_node_status_capacity{cluster_name=\"$cluster\", node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "CPU Requests of all pods on the node"
    }
   ]
  },
  {
   "title": "CPU Usage(millicores)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster_name=\"$cluster\", job=\"kubernetes-pods\", node=~\"$node\", resource=\"cpu\"}) * 1000",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{instance=~\"$node\", container!=\"\", container!=\"POD\"}[60s])) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota(millicores)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)* 1000"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}[5m])) by (pod) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod) * 1000"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Requests vs Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"}) / sum(kube_node_status_capacity{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"})",
       "legendFormat": "Memory Requests of all pods on the node"
      }
     ]
    },
    {
     "title": "Memory Usage (w/cache)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"})",
       "legendFormat": "max capacity"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{instance=~\"$node\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"})",
       "legendFormat": "max capacity"
      },
      {
       "expr": "sum(container_memory_rss{instance=~\"$node\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{cluster_name=\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{cluster_name=\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}