{
 "title": "Velero",
 "description": "Velero backup stats",
 "tags": [ "velero" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Total",
   "type": "stat",
   "description": "The sum of one-off backup and schedule backup success total ",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_backup_total" }
   ]
  },
  {
   "title": "Backup Last Status",
   "type": "stat",
   "description": "The last status of the backup. A value of 1 indicates success, while a value of 0 indicates failure.",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_backup_last_status" }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Volume snapshot Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}) / sum(velero_volume_snapshot_attempt_total{schedule=~\"$schedule\"})\n"
    }
   ]
  },
  {
   "title": "Backup Deletion Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_deletion_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_deletion_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table",
   "description": "for schedule backup use only",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule!=\"\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(velero_backup_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup success"
    },
    {
     "expr": "round(sum(increase(velero_backup_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup partial failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion success"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion failure"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_total{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items total"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_errors{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items errors_total"
    },
    {
     "expr": "round(sum(increase(velero_backup_validation_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup validation failure"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_warning_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup warning"
    }
   ]
  },
  {
   "title": "Backup time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\",le!=\"+Inf\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Kopia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Kopia Transfer Volumes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kopia_blob_download_full_blob_bytes_total",
     "legendFormat": "Full Downloads"
    },
    {
     "expr": "kopia_blob_download_partial_blob_bytes_total",
     "legendFormat": "Partial Downloads"
    },
    { "expr": "kopia_blob_upload_bytes_total", "legendFormat": "Uploads" }
   ]
  },
  {
   "title": "Kopia Operation Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kopia_blob_storage_latency_ms_sum{method=~\"GetBlob.*|PutBlob|ListBlobs\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Kopia Errors by Operation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kopia_blob_errors_total) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Kopia Cache Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kopia_cache_hit_bytes_total[5m])",
     "legendFormat": "Cache Hits {{cache}}"
    },
    {
     "expr": "rate(kopia_cache_miss_bytes_total[5m])",
     "legendFormat": "Cache Misses {{cache}}"
    }
   ]
  },
  { "title": "Restore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Restore Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_restore_total" }
   ]
  },
  {
   "title": "Restore Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_restore_success_total{schedule=~\"$schedule\"}) / sum(velero_restore_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Restore per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(velero_restore_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore success"
    },
    {
     "expr": "round(sum(increase(velero_restore_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_validation_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore validation failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore partial failure"
    }
   ]
  }
 ]
}