// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface _SMARTAuthorizationHooks$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "_SMARTAuthorizationHooks",
  "sourceName": "smart-protocol/contracts/extensions/core/internal/_SMARTAuthorizationHooks.sol",
  "abi": [],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "_SMARTAuthorizationHooks",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>>;
  export function deployContract(
    contractName: "smart-protocol/contracts/extensions/core/internal/_SMARTAuthorizationHooks.sol:_SMARTAuthorizationHooks",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "_SMARTAuthorizationHooks",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "smart-protocol/contracts/extensions/core/internal/_SMARTAuthorizationHooks.sol:_SMARTAuthorizationHooks",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "_SMARTAuthorizationHooks",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>>;
  export function getContractAt(
    contractName: "smart-protocol/contracts/extensions/core/internal/_SMARTAuthorizationHooks.sol:_SMARTAuthorizationHooks",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>>;
}
