// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { _SMARTAuthorizationHooks$Type } from "./_SMARTAuthorizationHooks";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["_SMARTAuthorizationHooks"]: _SMARTAuthorizationHooks$Type;
    ["smart-protocol/contracts/extensions/core/internal/_SMARTAuthorizationHooks.sol:_SMARTAuthorizationHooks"]: _SMARTAuthorizationHooks$Type;
  }

  interface ContractTypesMap {
    ["_SMARTAuthorizationHooks"]: GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>;
    ["smart-protocol/contracts/extensions/core/internal/_SMARTAuthorizationHooks.sol:_SMARTAuthorizationHooks"]: GetContractReturnType<_SMARTAuthorizationHooks$Type["abi"]>;
  }
}
