apiVersion: v2
name: thegraph
description: A Helm chart for the blockscout components
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: graph-node
    version: 0.5.9
    repository: http://graphops.github.io/launchpad-charts
