apiVersion: v2
name: thegraph
description: A Helm chart for the blockscout components
type: application
version: 1.0.6-pr
appVersion: 1.0.6-pr
icon: https://console.settlemint.com/android-chrome-512x512.png
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
dependencies:
  - name: graph-node
    version: 0.5.9
    repository: http://graphops.github.io/launchpad-charts
