// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC3643TrustedIssuersRegistry$Type } from "./IERC3643TrustedIssuersRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC3643TrustedIssuersRegistry"]: IERC3643TrustedIssuersRegistry$Type;
    ["contracts/smart/interface/ERC-3643/IERC3643TrustedIssuersRegistry.sol:IERC3643TrustedIssuersRegistry"]: IERC3643TrustedIssuersRegistry$Type;
  }

  interface ContractTypesMap {
    ["IERC3643TrustedIssuersRegistry"]: GetContractReturnType<
      IERC3643TrustedIssuersRegistry$Type["abi"]
    >;
    ["contracts/smart/interface/ERC-3643/IERC3643TrustedIssuersRegistry.sol:IERC3643TrustedIssuersRegistry"]: GetContractReturnType<
      IERC3643TrustedIssuersRegistry$Type["abi"]
    >;
  }
}
