DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS private_keys CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS verification_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS provider_type CASCADE;