// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISMARTBurnable$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ISMARTBurnable",
  "sourceName": "smart-protocol/contracts/extensions/burnable/ISMARTBurnable.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address[]",
          "name": "userAddresses",
          "type": "address[]"
        },
        {
          "internalType": "uint256[]",
          "name": "amounts",
          "type": "uint256[]"
        }
      ],
      "name": "batchBurn",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "userAddress",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "burn",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISMARTBurnable",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTBurnable$Type["abi"]>>;
  export function deployContract(
    contractName: "smart-protocol/contracts/extensions/burnable/ISMARTBurnable.sol:ISMARTBurnable",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTBurnable$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISMARTBurnable",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTBurnable$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "smart-protocol/contracts/extensions/burnable/ISMARTBurnable.sol:ISMARTBurnable",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTBurnable$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISMARTBurnable",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTBurnable$Type["abi"]>>;
  export function getContractAt(
    contractName: "smart-protocol/contracts/extensions/burnable/ISMARTBurnable.sol:ISMARTBurnable",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTBurnable$Type["abi"]>>;
}
