// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AbstractATKSystemAddonFactoryImplementation$Type } from "./AbstractATKSystemAddonFactoryImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AbstractATKSystemAddonFactoryImplementation"]: AbstractATKSystemAddonFactoryImplementation$Type;
    ["contracts/system/AbstractATKSystemAddonFactoryImplementation.sol:AbstractATKSystemAddonFactoryImplementation"]: AbstractATKSystemAddonFactoryImplementation$Type;
  }

  interface ContractTypesMap {
    ["AbstractATKSystemAddonFactoryImplementation"]: GetContractReturnType<AbstractATKSystemAddonFactoryImplementation$Type["abi"]>;
    ["contracts/system/AbstractATKSystemAddonFactoryImplementation.sol:AbstractATKSystemAddonFactoryImplementation"]: GetContractReturnType<AbstractATKSystemAddonFactoryImplementation$Type["abi"]>;
  }
}
