// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKTopicSchemeRegistryProxy$Type } from "./ATKTopicSchemeRegistryProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKTopicSchemeRegistryProxy"]: ATKTopicSchemeRegistryProxy$Type;
    ["contracts/system/topic-scheme-registry/ATKTopicSchemeRegistryProxy.sol:ATKTopicSchemeRegistryProxy"]: ATKTopicSchemeRegistryProxy$Type;
  }

  interface ContractTypesMap {
    ["ATKTopicSchemeRegistryProxy"]: GetContractReturnType<ATKTopicSchemeRegistryProxy$Type["abi"]>;
    ["contracts/system/topic-scheme-registry/ATKTopicSchemeRegistryProxy.sol:ATKTopicSchemeRegistryProxy"]: GetContractReturnType<ATKTopicSchemeRegistryProxy$Type["abi"]>;
  }
}
