// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKDepositFactory$Type } from "./IATKDepositFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKDepositFactory"]: IATKDepositFactory$Type;
    ["contracts/assets/deposit/IATKDepositFactory.sol:IATKDepositFactory"]: IATKDepositFactory$Type;
  }

  interface ContractTypesMap {
    ["IATKDepositFactory"]: GetContractReturnType<IATKDepositFactory$Type["abi"]>;
    ["contracts/assets/deposit/IATKDepositFactory.sol:IATKDepositFactory"]: GetContractReturnType<IATKDepositFactory$Type["abi"]>;
  }
}
