// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IATKXvPSettlementFactory$Type } from "./IATKXvPSettlementFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IATKXvPSettlementFactory"]: IATKXvPSettlementFactory$Type;
    ["contracts/addons/xvp/IATKXvPSettlementFactory.sol:IATKXvPSettlementFactory"]: IATKXvPSettlementFactory$Type;
  }

  interface ContractTypesMap {
    ["IATKXvPSettlementFactory"]: GetContractReturnType<
      IATKXvPSettlementFactory$Type["abi"]
    >;
    ["contracts/addons/xvp/IATKXvPSettlementFactory.sol:IATKXvPSettlementFactory"]: GetContractReturnType<
      IATKXvPSettlementFactory$Type["abi"]
    >;
  }
}
