// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SMARTIdentityFactory$Type } from "./SMARTIdentityFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SMARTIdentityFactory"]: SMARTIdentityFactory$Type;
    ["smart-protocol/contracts/SMARTIdentityFactory.sol:SMARTIdentityFactory"]: SMARTIdentityFactory$Type;
  }

  interface ContractTypesMap {
    ["SMARTIdentityFactory"]: GetContractReturnType<SMARTIdentityFactory$Type["abi"]>;
    ["smart-protocol/contracts/SMARTIdentityFactory.sol:SMARTIdentityFactory"]: GetContractReturnType<SMARTIdentityFactory$Type["abi"]>;
  }
}
