// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SMARTHistoricalBalances$Type } from "./SMARTHistoricalBalances";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SMARTHistoricalBalances"]: SMARTHistoricalBalances$Type;
    ["contracts/smart/extensions/historical-balances/SMARTHistoricalBalances.sol:SMARTHistoricalBalances"]: SMARTHistoricalBalances$Type;
  }

  interface ContractTypesMap {
    ["SMARTHistoricalBalances"]: GetContractReturnType<
      SMARTHistoricalBalances$Type["abi"]
    >;
    ["contracts/smart/extensions/historical-balances/SMARTHistoricalBalances.sol:SMARTHistoricalBalances"]: GetContractReturnType<
      SMARTHistoricalBalances$Type["abi"]
    >;
  }
}
