// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ATKAirdrop: never;
    IATKAirdrop: never;
    ATKAmountClaimTracker: never;
    IATKClaimTracker: never;
    ATKLinearVestingStrategy: never;
    ATKVestingAirdropFactoryImplementation: never;
    ATKVestingAirdropImplementation: never;
    ATKVestingAirdropProxy: never;
    IATKVestingAirdrop: never;
    IATKVestingAirdropFactory: never;
    IATKVestingStrategy: never;
    ATKFixedYieldProxy: never;
    ATKFixedYieldScheduleFactoryImplementation: never;
    IATKFixedYieldScheduleFactory: never;
  }

  interface ContractTypesMap {
    ATKAirdrop: never;
    IATKAirdrop: never;
    ATKAmountClaimTracker: never;
    IATKClaimTracker: never;
    ATKLinearVestingStrategy: never;
    ATKVestingAirdropFactoryImplementation: never;
    ATKVestingAirdropImplementation: never;
    ATKVestingAirdropProxy: never;
    IATKVestingAirdrop: never;
    IATKVestingAirdropFactory: never;
    IATKVestingStrategy: never;
    ATKFixedYieldProxy: never;
    ATKFixedYieldScheduleFactoryImplementation: never;
    IATKFixedYieldScheduleFactory: never;
  }
}
