// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Structs$Type } from "./Structs";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Structs"]: Structs$Type;
    ["@onchainid/contracts/storage/Structs.sol:Structs"]: Structs$Type;
  }

  interface ContractTypesMap {
    ["Structs"]: GetContractReturnType<Structs$Type["abi"]>;
    ["@onchainid/contracts/storage/Structs.sol:Structs"]: GetContractReturnType<Structs$Type["abi"]>;
  }
}
