// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Structs$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Structs",
  "sourceName": "@onchainid/contracts/storage/Structs.sol",
  "abi": [],
  "bytecode": "0x60808060405234601357603a908160198239f35b600080fdfe600080fdfea2646970667358221220d6d10faff3caa307956ed00af780ce0687b533136c79b1cf3e8dfee7b492dc2264736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea2646970667358221220d6d10faff3caa307956ed00af780ce0687b533136c79b1cf3e8dfee7b492dc2264736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Structs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Structs$Type["abi"]>>;
  export function deployContract(
    contractName: "@onchainid/contracts/storage/Structs.sol:Structs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Structs$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Structs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Structs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@onchainid/contracts/storage/Structs.sol:Structs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Structs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Structs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Structs$Type["abi"]>>;
  export function getContractAt(
    contractName: "@onchainid/contracts/storage/Structs.sol:Structs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Structs$Type["abi"]>>;
}
