// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISMARTYield$Type {
  _format: "hh-sol-artifact-1";
  contractName: "ISMARTYield";
  sourceName: "contracts/smart/extensions/yield/ISMARTYield.sol";
  abi: [
    {
      inputs: [
        {
          internalType: "uint256";
          name: "requestedTimepoint";
          type: "uint256";
        },
        {
          internalType: "uint48";
          name: "currentTimepoint";
          type: "uint48";
        },
      ];
      name: "FutureLookup";
      type: "error";
    },
    {
      inputs: [];
      name: "YieldScheduleActive";
      type: "error";
    },
    {
      inputs: [];
      name: "YieldScheduleAlreadySet";
      type: "error";
    },
    {
      anonymous: false;
      inputs: [
        {
          indexed: true;
          internalType: "address";
          name: "sender";
          type: "address";
        },
        {
          indexed: true;
          internalType: "address";
          name: "account";
          type: "address";
        },
        {
          indexed: false;
          internalType: "uint256";
          name: "oldBalance";
          type: "uint256";
        },
        {
          indexed: false;
          internalType: "uint256";
          name: "newBalance";
          type: "uint256";
        },
      ];
      name: "CheckpointUpdated";
      type: "event";
    },
    {
      anonymous: false;
      inputs: [
        {
          indexed: true;
          internalType: "address";
          name: "sender";
          type: "address";
        },
        {
          indexed: true;
          internalType: "address";
          name: "schedule";
          type: "address";
        },
      ];
      name: "YieldScheduleSet";
      type: "event";
    },
    {
      inputs: [
        {
          internalType: "address";
          name: "account";
          type: "address";
        },
        {
          internalType: "uint256";
          name: "timepoint";
          type: "uint256";
        },
      ];
      name: "balanceOfAt";
      outputs: [
        {
          internalType: "uint256";
          name: "";
          type: "uint256";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "address";
          name: "schedule";
          type: "address";
        },
      ];
      name: "setYieldSchedule";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "uint256";
          name: "timepoint";
          type: "uint256";
        },
      ];
      name: "totalSupplyAt";
      outputs: [
        {
          internalType: "uint256";
          name: "";
          type: "uint256";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "address";
          name: "holder";
          type: "address";
        },
      ];
      name: "yieldBasisPerUnit";
      outputs: [
        {
          internalType: "uint256";
          name: "basisPerUnit";
          type: "uint256";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [];
      name: "yieldSchedule";
      outputs: [
        {
          internalType: "address";
          name: "schedule";
          type: "address";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [];
      name: "yieldToken";
      outputs: [
        {
          internalType: "contract IERC20";
          name: "paymentToken";
          type: "address";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISMARTYield",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTYield$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/smart/extensions/yield/ISMARTYield.sol:ISMARTYield",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISMARTYield$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISMARTYield",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTYield$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/smart/extensions/yield/ISMARTYield.sol:ISMARTYield",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISMARTYield$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISMARTYield",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTYield$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/smart/extensions/yield/ISMARTYield.sol:ISMARTYield",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISMARTYield$Type["abi"]>>;
}
