name: Generate Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate-artifacts:
    name: Generate and Commit Artifacts
    runs-on: namespace-profile-atk
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up turbo caching
        uses: namespace-actions/setup-turbocache@v0

      - name: Setup bun caches
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ./node_modules
            ./.turbo
            ./**/.turbo
            ~/.bun/install/cache

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install dependencies
        run: bun install

      - name: Launch docker compose
        run: bun run dev:up

      - name: Generate artifacts
        run: bunx turbo run artifacts
        env:
          TURBO_FORCE: true

      - name: Auto-commit artifacts
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "chore: update artifacts [skip ci]"
          branch: main
          file_pattern: |
            tools/docker/besu/genesis.json
            tools/docker/portal/*.json
            tools/docker/postgres/atk.sql
          commit_options: '--no-verify'
          skip_dirty_check: false
          skip_checkout: true

      - name: Store generated artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-artifacts
          path: |
            tools/docker/besu/genesis.json
            tools/docker/portal/*.json
            tools/docker/postgres/atk.sql
          retention-days: 30
