name: nightly

on:
  schedule:
    - cron: "0 4 * * *" # Run at 4:00 AM UTC daily
  workflow_dispatch: # Allow manual triggering from GitHub UI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly:
    name: Nightly
    uses: ./.github/workflows/reusable-qa.yml
    with:
      use-pat-token: true
      turbo-command: |
        bun run ci:gha:nightly --concurrency=100% --continue=dependencies-successful
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  secret-scanning:
    name: Secret Scanning
    uses: ./.github/workflows/reusable-secret-scanning.yml
    with:
      trivy-config: trivy-secret.yaml
      severity: "HIGH,CRITICAL"

  codeql:
    name: CodeQL
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      language: "javascript-typescript"
      build-mode: "none"
