name: PR Labels

on:
  pull_request:
    types: [opened, closed]
    branches:
      - main

permissions:
  contents: read # the config file
  issues: write # for labeling issues (on: issues)
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)
  statuses: write # to generate status
  checks: write # to generate status

jobs:
  labels:
    runs-on: namespace-profile-starterkit
    steps:
      - uses: fuxingloh/multi-labeler@b15a54460c38f54043fa75f7b08a0e2aa5b94b5b # v4
