name: QA - Main Branch

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  qa:
    name: QA
    uses: ./.github/workflows/reusable-qa.yml
    with:
      runs-on: namespace-profile-atk
      fetch-depth: 2
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  codeql:
    name: CodeQL Analysis
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      language: 'javascript-typescript'
      build-mode: 'none'
      runs-on: 'namespace-profile-atk-services'
