name: QA - Pull Request

on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        converted_to_draft,
        closed,
        review_requested,
        edited,
      ]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Label PR based on draft/ready status
  label-pr-status:
    name: Label PR Status
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'opened' ||
       github.event.action == 'ready_for_review' ||
       github.event.action == 'converted_to_draft' ||
       github.event.action == 'synchronize')
    uses: ./.github/workflows/reusable-pr-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      is_draft: ${{ github.event.pull_request.draft }}
      runs-on: namespace-profile-atk-services

  # Label PR as QA running when workflow starts (skip pending label)
  label-qa-start:
    name: Label QA Start
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-build-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      workflow_status: 'running'
      runs-on: namespace-profile-atk-services
  qa:
    name: QA
    needs: label-qa-start
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-qa.yml
    with:
      runs-on: namespace-profile-atk
      fetch-depth: 2
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  pr-labels:
    name: PR Labels
    if: |
      github.event.action == 'opened' || 
      github.event.action == 'synchronize' ||
      github.event.action == 'edited'
    uses: ./.github/workflows/reusable-pr-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_body: ${{ github.event.pull_request.body }}
      runs-on: namespace-profile-atk-services

  secret-scanning:
    name: Secret Scanning
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-secret-scanning.yml
    with:
      runs-on: namespace-profile-atk-services
      trivy-config: trivy-secret.yaml
      severity: "HIGH,CRITICAL"

  codeql:
    name: CodeQL Analysis
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      language: 'javascript-typescript'
      build-mode: 'none'
      runs-on: 'namespace-profile-atk-services'

  # Label PR with final QA status
  label-qa-end:
    name: Label QA End
    needs: [qa, secret-scanning]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-build-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      workflow_status: ${{ (needs.qa.result == 'success' && needs.secret-scanning.result != 'failure') && 'success' || 'failure' }}
      runs-on: namespace-profile-atk-services

  # Update PR status with review and QA information
  update-pr-status:
    name: Update PR Status
    needs: [label-qa-end, qa, secret-scanning]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'synchronize' || github.event.action == 'opened' || 
       github.event.action == 'ready_for_review' || github.event.action == 'converted_to_draft')
    runs-on: namespace-profile-atk-services
    steps:
      - name: Get PR reviews
        id: check_approval
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = ${{ github.event.pull_request.number }};
            
            // Get reviews
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            
            // Check if PR has approval (excluding the PR author)
            const pr_author = `${{ github.event.pull_request.user.login }}`;
            const has_approval = reviews.data.some(review => 
              review.state === 'APPROVED' && 
              review.user.login !== pr_author
            );
            
            core.setOutput('has_approval', has_approval);
            
      - name: Determine QA status
        id: qa_status
        run: |
          if [[ "${{ needs.qa.result }}" == "success" && "${{ needs.secret-scanning.result }}" != "failure" ]]; then
            echo "qa_status=success" >> $GITHUB_OUTPUT
          else
            echo "qa_status=failed" >> $GITHUB_OUTPUT
          fi
    outputs:
      has_approval: ${{ steps.check_approval.outputs.has_approval }}
      qa_status: ${{ steps.qa_status.outputs.qa_status }}

  # Apply final PR status label
  label-pr-final-status:
    name: Label PR Final Status
    needs: [update-pr-status]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]')
    uses: ./.github/workflows/reusable-pr-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      is_draft: ${{ github.event.pull_request.draft }}
      has_approval: ${{ fromJson(needs.update-pr-status.outputs.has_approval) }}
      qa_status: ${{ needs.update-pr-status.outputs.qa_status }}
      runs-on: namespace-profile-atk-services

  # Enable auto-merge if PR is mergeable
  enable-auto-merge:
    name: Enable Auto-Merge
    needs: [update-pr-status, label-pr-final-status]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      needs.update-pr-status.outputs.has_approval == 'true' &&
      needs.update-pr-status.outputs.qa_status == 'success' &&
      github.event.pull_request.draft == false
    runs-on: namespace-profile-atk-services
    steps:
      - name: Enable auto-merge for PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = ${{ github.event.pull_request.number }};
            
            try {
              // Enable auto-merge
              const result = await github.rest.pulls.enableAutoMerge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number,
                merge_method: 'squash' // or 'merge' or 'rebase' based on your preference
              });
              
              console.log(`Auto-merge enabled for PR #${pr_number}`);
            } catch (error) {
              console.log(`Failed to enable auto-merge: ${error.message}`);
              
              // Check if it's because auto-merge is already enabled
              if (error.message.includes('already enabled')) {
                console.log('Auto-merge is already enabled for this PR');
              } else if (error.message.includes('Auto-merge is not allowed')) {
                console.log('Auto-merge is not allowed for this repository. Please enable it in repository settings.');
              }
            }
