name: QA - Pull Request

on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        converted_to_draft,
        closed,
        review_requested,
      ]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Label PR based on draft/ready status
  label-pr-status:
    name: Label PR Status
    if: |
      github.event.action == 'opened' ||
      github.event.action == 'ready_for_review' ||
      github.event.action == 'converted_to_draft'
    uses: ./.github/workflows/reusable-pr-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      is_draft: ${{ github.event.pull_request.draft }}

  # Label PR as QA running when workflow starts
  label-qa-start:
    name: Label QA Start
    if: |
      github.event.action == 'synchronize' || github.event.action == 'opened'
    uses: ./.github/workflows/reusable-build-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      workflow_status: 'running'
  qa:
    name: QA
    needs: label-qa-start
    if: |
      github.event.action == 'synchronize' || github.event.action == 'opened'
    uses: ./.github/workflows/reusable-qa.yml
    with:
      runs-on: namespace-profile-atk
      fetch-depth: 2
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  pr-labels:
    name: PR Labels
    uses: ./.github/workflows/reusable-pr-labels.yml

  secret-scanning:
    name: Secret Scanning
    if: |
      github.event.action == 'synchronize' || github.event.action == 'opened'
    uses: ./.github/workflows/reusable-secret-scanning.yml
    with:
      trivy-config: trivy-secret.yaml
      severity: "HIGH,CRITICAL"

  codeql:
    name: CodeQL Analysis
    if: |
      github.event.action == 'synchronize' || github.event.action == 'opened'
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      language: 'javascript-typescript'
      build-mode: 'none'
      runs-on: 'namespace-profile-atk'

  # Label PR with final QA status
  label-qa-end:
    name: Label QA End
    needs: [qa, secret-scanning]
    if: |
      always() &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-build-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      workflow_status: ${{ (needs.qa.result == 'success' && needs.secret-scanning.result != 'failure') && 'success' || 'failure' }}