name: QA - Pull Request

on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        converted_to_draft,
        closed,
        review_requested,
        edited,
      ]
    branches:
      - main
  pull_request_review:
    types: [submitted, dismissed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Label PR based on draft/ready status
  label-pr-status:
    name: Label PR Status
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      github.event_name == 'pull_request' &&
      (github.event.action == 'opened' ||
       github.event.action == 'ready_for_review' ||
       github.event.action == 'converted_to_draft' ||
       github.event.action == 'synchronize')
    uses: ./.github/workflows/reusable-pr-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      is_draft: ${{ github.event.pull_request.draft }}
      runs-on: namespace-profile-atk-services

  # Label PR as QA running when workflow starts (skip pending label)
  label-qa-start:
    name: Label QA Start
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      github.event_name == 'pull_request' &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-build-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      workflow_status: 'running'
      runs-on: namespace-profile-atk-services
  qa:
    name: QA
    needs: label-qa-start
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      github.event_name == 'pull_request' &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-qa.yml
    with:
      runs-on: namespace-profile-atk
      fetch-depth: 2
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  pr-labels:
    name: PR Labels
    if: |
      github.event_name == 'pull_request' &&
      (github.event.action == 'opened' || 
       github.event.action == 'synchronize' ||
       github.event.action == 'edited')
    uses: ./.github/workflows/reusable-pr-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_body: ${{ github.event.pull_request.body }}
      runs-on: namespace-profile-atk-services

  secret-scanning:
    name: Secret Scanning
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      github.event_name == 'pull_request' &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-secret-scanning.yml
    with:
      runs-on: namespace-profile-atk-services
      trivy-config: trivy-secret.yaml
      severity: "HIGH,CRITICAL"

  codeql:
    name: CodeQL Analysis
    if: |
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      github.event_name == 'pull_request' &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-codeql.yml
    with:
      language: 'javascript-typescript'
      build-mode: 'none'
      runs-on: 'namespace-profile-atk-services'

  # Label PR with final QA status
  label-qa-end:
    name: Label QA End
    needs: [qa, secret-scanning]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      github.event_name == 'pull_request' &&
      (github.event.action == 'synchronize' || github.event.action == 'opened')
    uses: ./.github/workflows/reusable-build-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      workflow_status: ${{ (needs.qa.result == 'success' && needs.secret-scanning.result == 'success') && 'success' || 'failure' }}
      runs-on: namespace-profile-atk-services

  # Update PR status with review and QA information
  update-pr-status:
    name: Update PR Status
    needs: [label-qa-end, qa, secret-scanning]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]') &&
      (github.event.action == 'synchronize' || github.event.action == 'opened' || 
       github.event.action == 'ready_for_review' || github.event.action == 'converted_to_draft' ||
       github.event.action == 'submitted' || github.event.action == 'dismissed')
    runs-on: namespace-profile-atk-services
    steps:
      - name: Get PR reviews
        id: check_approval
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = ${{ github.event.pull_request.number }};
            
            // Get reviews
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            
            // Check if PR has approval (excluding the PR author)
            const pr_author = `${{ github.event.pull_request.user.login }}`;
            const has_approval = reviews.data.some(review => 
              review.state === 'APPROVED' && 
              review.user.login !== pr_author
            );
            
            core.setOutput('has_approval', has_approval);
            
      - name: Determine QA status
        id: qa_status
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = ${{ github.event.pull_request.number }};
            
            // For review events, we need to check labels since qa job doesn't run
            if ('${{ github.event_name }}' === 'pull_request_review') {
              // Get current labels
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number
              });
              
              const labels = pr.labels.map(l => l.name);
              let qa_status = '';
              
              if (labels.includes('qa:success')) {
                qa_status = 'success';
              } else if (labels.includes('qa:failed')) {
                qa_status = 'failed';
              } else if (labels.includes('qa:running')) {
                qa_status = 'running';
              } else if (labels.includes('qa:pending')) {
                qa_status = 'pending';
              }
              
              core.setOutput('qa_status', qa_status);
            } else {
              // For PR events, use the job results
              if ('${{ needs.qa.result }}' === 'success' && '${{ needs.secret-scanning.result }}' === 'success') {
                core.setOutput('qa_status', 'success');
              } else {
                core.setOutput('qa_status', 'failed');
              }
            }
    outputs:
      has_approval: ${{ steps.check_approval.outputs.has_approval }}
      qa_status: ${{ steps.qa_status.outputs.qa_status }}

  # Apply final PR status label
  label-pr-final-status:
    name: Label PR Final Status
    needs: [update-pr-status]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]')
    uses: ./.github/workflows/reusable-pr-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      is_draft: ${{ github.event.pull_request.draft }}
      has_approval: ${{ needs.update-pr-status.outputs.has_approval == 'true' }}
      qa_status: ${{ needs.update-pr-status.outputs.qa_status }}
      runs-on: namespace-profile-atk-services

  # Handle PR closed/merged
  label-pr-closed:
    name: Label PR Closed
    if: |
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      !endsWith(github.event.pull_request.user.login, '[bot]')
    uses: ./.github/workflows/reusable-pr-status-labeler.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      is_draft: ${{ github.event.pull_request.draft }}
      is_merged: ${{ github.event.pull_request.merged }}
      runs-on: namespace-profile-atk-services

  # Manage auto-merge based on PR state
  manage-auto-merge:
    name: Manage Auto-Merge
    needs: [update-pr-status, label-pr-final-status]
    if: |
      always() &&
      !endsWith(github.event.pull_request.user.login, '[bot]')
    runs-on: namespace-profile-atk-services
    steps:
      - name: Manage auto-merge for PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = ${{ github.event.pull_request.number }};
            const has_approval = '${{ needs.update-pr-status.outputs.has_approval }}' === 'true';
            const qa_status = '${{ needs.update-pr-status.outputs.qa_status }}';
            const is_draft = ${{ github.event.pull_request.draft }};
            
            // Check if PR is mergeable
            const is_mergeable = has_approval && qa_status === 'success' && !is_draft;
            
            try {
              if (is_mergeable) {
                // Enable auto-merge
                await github.rest.pulls.enableAutoMerge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr_number,
                  merge_method: 'squash'
                });
                console.log(`Auto-merge enabled for PR #${pr_number}`);
              } else {
                // Disable auto-merge if it was enabled
                await github.rest.pulls.disableAutoMerge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr_number
                });
                console.log(`Auto-merge disabled for PR #${pr_number} - no longer mergeable`);
              }
            } catch (error) {
              if (error.message.includes('Auto-merge is not enabled')) {
                console.log('Auto-merge is already disabled');
              } else if (error.message.includes('already enabled')) {
                console.log('Auto-merge is already enabled');
              } else if (error.message.includes('Auto-merge is not allowed')) {
                console.log('Auto-merge is not allowed for this repository. Please enable it in repository settings.');
              } else {
                console.log(`Error managing auto-merge: ${error.message}`);
              }
            }
