name: Artifacts (Reusable)

# This is a reusable workflow for running the artifacts job
# which includes setup, turbo command, artifact upload, and auto-commit.
#
# Usage:
# ```yaml
# jobs:
#   artifacts:
#     uses: ./.github/workflows/reusable-artifacts.yml
#     with:
#       runs-on: 'namespace-profile-atk'  # optional, defaults to 'namespace-profile-atk'
#     secrets:
#       OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
# ```

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Runner to use for the job"
        required: false
        type: string
        default: "namespace-profile-atk"
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  checks: write
  packages: write
  id-token: write

jobs:
  artifacts:
    name: Artifacts
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Setup 1Password
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        env:
          HARBOR_USER: op://platform/harbor/username
          HARBOR_PASS: op://platform/harbor/password
          PAT_TOKEN: op://platform/github-commit-pat/credential

      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@v7
        with:
          fetch-depth: 2
          token: ${{ env.PAT_TOKEN }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Set up turbo caching
        uses: namespace-actions/setup-turbocache@v0

      - name: Setup bun caches
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ./node_modules
            ./.turbo
            ./**/.turbo
            ~/.bun/install/cache

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Harbor
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: harbor.settlemint.com
          username: ${{ env.HARBOR_USER }}
          password: ${{ env.HARBOR_PASS }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Helm Docs
        run: |
          brew install norwoodj/tap/helm-docs

      - name: Install Bun dependencies
        run: bun install

      - name: Launch docker compose
        run: |
          bun run dev:up

      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4

      - name: Turbo
        run: |
          bun run ci:gha:artifacts --concurrency=100%
        env:
          THE_GRAPH_PORT_LOCAL_DEPLOY: 8120 # For subgraph tests
          THE_GRAPH_PORT_LOCAL_QUERY: 8100 # For subgraph tests

      - name: Store predeployed output
        uses: actions/upload-artifact@v4
        with:
          name: predeployed-output
          path: |
            kit/contracts/tools/genesis-output.json
            kit/contracts/portal/*.json
            kit/subgraph/subgraph-output.txt

      - name: Auto-commit artifacts
        if: |
          github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' &&
          github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "chore: update artifacts [skip ci]"
          branch: main
          file_pattern: |
            tools/docker/
            docker-compose.yml
            kit/dapp/locales/**/*.json
            kit/charts/**/README.md
