name: Slack PR Notifications

on:
  pull_request:
    types: [labeled, unlabeled]

permissions:
  pull-requests: write
  issues: read

jobs:
  # Check if we should notify based on the label change
  check-notification:
    name: Check Notification
    runs-on: namespace-profile-atk-services
    outputs:
      should_notify: ${{ steps.check.outputs.should_notify }}
      pr_labels: ${{ steps.check.outputs.pr_labels }}
    steps:
      - name: Check if notification is needed
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const label = context.payload.label;
            const action = context.payload.action;

            // List of labels we care about for notifications
            const notificationLabels = [
              'qa:pending', 'qa:running', 'qa:success', 'qa:failed',
              'status:draft', 'status:ready-for-review', 'status:approved',
              'status:mergeable', 'status:merged'
            ];

            // Check if the label that was added/removed is one we care about
            const shouldNotify = notificationLabels.includes(label.name);

            // Get all current labels on the PR
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const prLabels = JSON.stringify(pr.labels);

            core.setOutput('should_notify', shouldNotify);
            core.setOutput('pr_labels', prLabels);

            console.log(`Label ${action}: ${label.name}`);
            console.log(`Should notify: ${shouldNotify}`);

  # Send or update Slack notification
  slack-notify:
    name: Slack Notification
    needs: check-notification
    if: needs.check-notification.outputs.should_notify == 'true'
    uses: ./.github/workflows/reusable-slack-pr-notifier.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_labels: ${{ needs.check-notification.outputs.pr_labels }}
      action: ${{ github.event.action }}
      runs-on: namespace-profile-atk-services
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}