{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        # Allow traffic from pods in the same namespace with specific labels
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: erpc
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: portal
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: hasura
        {{- range .Values.networkPolicy.allowedPodSelectors }}
        - podSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- range .Values.networkPolicy.allowedNamespaceSelectors }}
        - namespaceSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
{{- end }}