{{- if index .Values "graph-node" "ingress" "enabled" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph-node-ingress
  labels:
    {{- include "thegraph.labels" . | nindent 4 }}
  {{- with index .Values "graph-node" "ingress" "annotations" }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with index .Values "graph-node" "ingress" "className" }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if index .Values "graph-node" "ingress" "tls" }}
  tls:
    {{- range index .Values "graph-node" "ingress" "tls" }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range index .Values "graph-node" "ingress" "hosts" }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}
