apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "thegraph.fullname" . }}-workspace
  labels:
    {{- include "thegraph.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.job.workspace.size | default "1Gi" }}
  {{- if .Values.job.workspace.storageClass }}
  storageClassName: {{ .Values.job.workspace.storageClass | default "" }}
  {{- end }}
