apiVersion: v1
kind: Secret
metadata:
  name: thegraph-pg-secret
  labels:
    {{- include "thegraph.labels" . | nindent 4 }}
data:
  PGUSER: {{ index .Values "graph-node" "customSecret" "PGUSER" | b64enc }}
  PGPASSWORD: {{ index .Values "graph-node" "customSecret" "PGPASSWORD" | b64enc }}

