// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ATKFundFactoryImplementation$Type } from "./ATKFundFactoryImplementation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ATKFundFactoryImplementation"]: ATKFundFactoryImplementation$Type;
    ["contracts/assets/fund/ATKFundFactoryImplementation.sol:ATKFundFactoryImplementation"]: ATKFundFactoryImplementation$Type;
  }

  interface ContractTypesMap {
    ["ATKFundFactoryImplementation"]: GetContractReturnType<
      ATKFundFactoryImplementation$Type["abi"]
    >;
    ["contracts/assets/fund/ATKFundFactoryImplementation.sol:ATKFundFactoryImplementation"]: GetContractReturnType<
      ATKFundFactoryImplementation$Type["abi"]
    >;
  }
}
